/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { AccountCreateDto } from './models/AccountCreateDto';
export { AccountDto } from './models/AccountDto';
export type { AccountDtoEnvelope } from './models/AccountDtoEnvelope';
export type { AccountDtoListEnvelope } from './models/AccountDtoListEnvelope';
export type { AccountGroupCreateDto } from './models/AccountGroupCreateDto';
export type { AccountGroupDto } from './models/AccountGroupDto';
export type { AccountGroupDtoEnvelope } from './models/AccountGroupDtoEnvelope';
export type { AccountGroupDtoListEnvelope } from './models/AccountGroupDtoListEnvelope';
export type { AccountGroupUpdateDto } from './models/AccountGroupUpdateDto';
export { AccountingEntryCreateDto } from './models/AccountingEntryCreateDto';
export { AccountingEntryDto } from './models/AccountingEntryDto';
export type { AccountingEntryDtoEnvelope } from './models/AccountingEntryDtoEnvelope';
export type { AccountingEntryDtoListEnvelope } from './models/AccountingEntryDtoListEnvelope';
export { AccountingEntryUpdateDto } from './models/AccountingEntryUpdateDto';
export type { AccountingPeriodCreateDto } from './models/AccountingPeriodCreateDto';
export type { AccountingPeriodDto } from './models/AccountingPeriodDto';
export type { AccountingPeriodDtoEnvelope } from './models/AccountingPeriodDtoEnvelope';
export type { AccountingPeriodDtoListEnvelope } from './models/AccountingPeriodDtoListEnvelope';
export type { AccountingPeriodUpdateDto } from './models/AccountingPeriodUpdateDto';
export type { AccountRelationCreateDto } from './models/AccountRelationCreateDto';
export type { AccountRelationDto } from './models/AccountRelationDto';
export type { AccountRelationDtoListEnvelope } from './models/AccountRelationDtoListEnvelope';
export type { AccountRelationUpdateDto } from './models/AccountRelationUpdateDto';
export type { AccountTypeCreateDto } from './models/AccountTypeCreateDto';
export type { AccountTypeDto } from './models/AccountTypeDto';
export type { AccountTypeDtoListEnvelope } from './models/AccountTypeDtoListEnvelope';
export type { AccountTypeUpdateDto } from './models/AccountTypeUpdateDto';
export { AccountUpdateDto } from './models/AccountUpdateDto';
export type { AppliedTaxPolicyRecordCreateDto } from './models/AppliedTaxPolicyRecordCreateDto';
export type { AppliedTaxPolicyRecordDto } from './models/AppliedTaxPolicyRecordDto';
export type { AppliedTaxPolicyRecordDtoEnvelope } from './models/AppliedTaxPolicyRecordDtoEnvelope';
export type { AppliedTaxPolicyRecordDtoListEnvelope } from './models/AppliedTaxPolicyRecordDtoListEnvelope';
export type { AppliedTaxPolicyRecordUpdateDto } from './models/AppliedTaxPolicyRecordUpdateDto';
export { BankAccountCreateDto } from './models/BankAccountCreateDto';
export { BankAccountDto } from './models/BankAccountDto';
export type { BankAccountDtoEnvelope } from './models/BankAccountDtoEnvelope';
export type { BankAccountDtoListEnvelope } from './models/BankAccountDtoListEnvelope';
export { BankAccountUpdateDto } from './models/BankAccountUpdateDto';
export type { BankCreateDto } from './models/BankCreateDto';
export type { BankDto } from './models/BankDto';
export type { BankDtoEnvelope } from './models/BankDtoEnvelope';
export type { BankDtoListEnvelope } from './models/BankDtoListEnvelope';
export { BankGuaranteeCreateDto } from './models/BankGuaranteeCreateDto';
export { BankGuaranteeDto } from './models/BankGuaranteeDto';
export type { BankGuaranteeDtoEnvelope } from './models/BankGuaranteeDtoEnvelope';
export type { BankGuaranteeDtoListEnvelope } from './models/BankGuaranteeDtoListEnvelope';
export { BankGuaranteeUpdateDto } from './models/BankGuaranteeUpdateDto';
export type { BankTransactionCreateDto } from './models/BankTransactionCreateDto';
export type { BankTransactionDto } from './models/BankTransactionDto';
export type { BankTransactionDtoEnvelope } from './models/BankTransactionDtoEnvelope';
export type { BankTransactionDtoListEnvelope } from './models/BankTransactionDtoListEnvelope';
export type { BankTransactionUpdateDto } from './models/BankTransactionUpdateDto';
export type { BankUpdateDto } from './models/BankUpdateDto';
export type { BillingProfileCreateDto } from './models/BillingProfileCreateDto';
export { BillingProfileDto } from './models/BillingProfileDto';
export type { BillingProfileDtoEnvelope } from './models/BillingProfileDtoEnvelope';
export type { BillingProfileDtoListEnvelope } from './models/BillingProfileDtoListEnvelope';
export type { BillingProfileUpdateDto } from './models/BillingProfileUpdateDto';
export { BudgetAccountEntryCreateDto } from './models/BudgetAccountEntryCreateDto';
export { BudgetAccountEntryDto } from './models/BudgetAccountEntryDto';
export type { BudgetAccountEntryDtoEnvelope } from './models/BudgetAccountEntryDtoEnvelope';
export type { BudgetAccountEntryDtoListEnvelope } from './models/BudgetAccountEntryDtoListEnvelope';
export { BudgetAccountEntryUpdateDto } from './models/BudgetAccountEntryUpdateDto';
export type { BudgetCreateDto } from './models/BudgetCreateDto';
export type { BudgetDto } from './models/BudgetDto';
export type { BudgetDtoEnvelope } from './models/BudgetDtoEnvelope';
export type { BudgetDtoListEnvelope } from './models/BudgetDtoListEnvelope';
export type { BudgetUpdateDto } from './models/BudgetUpdateDto';
export type { CommissionCreateDto } from './models/CommissionCreateDto';
export type { CommissionDto } from './models/CommissionDto';
export type { CommissionDtoListEnvelope } from './models/CommissionDtoListEnvelope';
export type { CommissionUpdateDto } from './models/CommissionUpdateDto';
export type { CostCentreBudgetCreateDto } from './models/CostCentreBudgetCreateDto';
export type { CostCentreBudgetDto } from './models/CostCentreBudgetDto';
export type { CostCentreBudgetDtoEnvelope } from './models/CostCentreBudgetDtoEnvelope';
export type { CostCentreBudgetDtoListEnvelope } from './models/CostCentreBudgetDtoListEnvelope';
export type { CostCentreBudgetUpdateDto } from './models/CostCentreBudgetUpdateDto';
export { CostCentreCreateDto } from './models/CostCentreCreateDto';
export { CostCentreDto } from './models/CostCentreDto';
export type { CostCentreDtoEnvelope } from './models/CostCentreDtoEnvelope';
export type { CostCentreDtoListEnvelope } from './models/CostCentreDtoListEnvelope';
export type { CostCentreGroupCreateDto } from './models/CostCentreGroupCreateDto';
export type { CostCentreGroupDto } from './models/CostCentreGroupDto';
export type { CostCentreGroupDtoEnvelope } from './models/CostCentreGroupDtoEnvelope';
export type { CostCentreGroupDtoListEnvelope } from './models/CostCentreGroupDtoListEnvelope';
export type { CostCentreGroupUpdateDto } from './models/CostCentreGroupUpdateDto';
export { CostCentreUpdateDto } from './models/CostCentreUpdateDto';
export type { CreateLedgerDto } from './models/CreateLedgerDto';
export type { Currency } from './models/Currency';
export type { EmptyEnvelope } from './models/EmptyEnvelope';
export type { ErrorEnvelope } from './models/ErrorEnvelope';
export type { FinancialBookCreateDto } from './models/FinancialBookCreateDto';
export type { FinancialBookDto } from './models/FinancialBookDto';
export type { FinancialBookDtoEnvelope } from './models/FinancialBookDtoEnvelope';
export type { FinancialBookDtoListEnvelope } from './models/FinancialBookDtoListEnvelope';
export type { FinancialBookUpdateDto } from './models/FinancialBookUpdateDto';
export type { FiscalAuthorityCreateDto } from './models/FiscalAuthorityCreateDto';
export type { FiscalAuthorityDto } from './models/FiscalAuthorityDto';
export type { FiscalAuthorityDtoEnvelope } from './models/FiscalAuthorityDtoEnvelope';
export type { FiscalAuthorityDtoListEnvelope } from './models/FiscalAuthorityDtoListEnvelope';
export type { FiscalAuthorityUpdateDto } from './models/FiscalAuthorityUpdateDto';
export type { FiscalIdentificationTypeCreateDto } from './models/FiscalIdentificationTypeCreateDto';
export type { FiscalIdentificationTypeDto } from './models/FiscalIdentificationTypeDto';
export type { FiscalIdentificationTypeDtoEnvelope } from './models/FiscalIdentificationTypeDtoEnvelope';
export type { FiscalIdentificationTypeDtoListEnvelope } from './models/FiscalIdentificationTypeDtoListEnvelope';
export type { FiscalIdentificationTypeUpdateDto } from './models/FiscalIdentificationTypeUpdateDto';
export type { FiscalPeriodCreateDto } from './models/FiscalPeriodCreateDto';
export type { FiscalPeriodDto } from './models/FiscalPeriodDto';
export type { FiscalPeriodDtoEnvelope } from './models/FiscalPeriodDtoEnvelope';
export type { FiscalPeriodDtoListEnvelope } from './models/FiscalPeriodDtoListEnvelope';
export type { FiscalPeriodUpdateDto } from './models/FiscalPeriodUpdateDto';
export type { FiscalRegimeCreateDto } from './models/FiscalRegimeCreateDto';
export type { FiscalRegimeDto } from './models/FiscalRegimeDto';
export type { FiscalRegimeDtoEnvelope } from './models/FiscalRegimeDtoEnvelope';
export type { FiscalRegimeDtoListEnvelope } from './models/FiscalRegimeDtoListEnvelope';
export type { FiscalRegimeUpdateDto } from './models/FiscalRegimeUpdateDto';
export type { FiscalResponsibilityCreateDto } from './models/FiscalResponsibilityCreateDto';
export type { FiscalResponsibilityDto } from './models/FiscalResponsibilityDto';
export type { FiscalResponsibilityDtoEnvelope } from './models/FiscalResponsibilityDtoEnvelope';
export type { FiscalResponsibilityDtoListEnvelope } from './models/FiscalResponsibilityDtoListEnvelope';
export type { FiscalResponsibilityRecordCreateDto } from './models/FiscalResponsibilityRecordCreateDto';
export type { FiscalResponsibilityRecordDto } from './models/FiscalResponsibilityRecordDto';
export type { FiscalResponsibilityRecordDtoEnvelope } from './models/FiscalResponsibilityRecordDtoEnvelope';
export type { FiscalResponsibilityRecordDtoListEnvelope } from './models/FiscalResponsibilityRecordDtoListEnvelope';
export type { FiscalResponsibilityRecordUpdateDto } from './models/FiscalResponsibilityRecordUpdateDto';
export type { FiscalResponsibilityUpdateDto } from './models/FiscalResponsibilityUpdateDto';
export type { FiscalYearCreateDto } from './models/FiscalYearCreateDto';
export type { FiscalYearDto } from './models/FiscalYearDto';
export type { FiscalYearDtoEnvelope } from './models/FiscalYearDtoEnvelope';
export type { FiscalYearDtoListEnvelope } from './models/FiscalYearDtoListEnvelope';
export type { FiscalYearUpdateDto } from './models/FiscalYearUpdateDto';
export type { GrantCreateDto } from './models/GrantCreateDto';
export type { GrantDto } from './models/GrantDto';
export type { GrantDtoEnvelope } from './models/GrantDtoEnvelope';
export type { GrantDtoListEnvelope } from './models/GrantDtoListEnvelope';
export type { GrantUpdateDto } from './models/GrantUpdateDto';
export type { Int32Envelope } from './models/Int32Envelope';
export { InvoiceEnumerationRangeCreateDto } from './models/InvoiceEnumerationRangeCreateDto';
export { InvoiceEnumerationRangeDto } from './models/InvoiceEnumerationRangeDto';
export type { InvoiceEnumerationRangeDtoEnvelope } from './models/InvoiceEnumerationRangeDtoEnvelope';
export type { InvoiceEnumerationRangeDtoListEnvelope } from './models/InvoiceEnumerationRangeDtoListEnvelope';
export { InvoiceEnumerationRangeUpdateDto } from './models/InvoiceEnumerationRangeUpdateDto';
export type { ItemTaxPolicyRecordCreateDto } from './models/ItemTaxPolicyRecordCreateDto';
export type { ItemTaxPolicyRecordDto } from './models/ItemTaxPolicyRecordDto';
export type { ItemTaxPolicyRecordDtoEnvelope } from './models/ItemTaxPolicyRecordDtoEnvelope';
export type { ItemTaxPolicyRecordDtoListEnvelope } from './models/ItemTaxPolicyRecordDtoListEnvelope';
export type { ItemTaxPolicyRecordUpdateDto } from './models/ItemTaxPolicyRecordUpdateDto';
export type { JournalCreateDto } from './models/JournalCreateDto';
export type { JournalDto } from './models/JournalDto';
export type { JournalDtoEnvelope } from './models/JournalDtoEnvelope';
export type { JournalDtoListEnvelope } from './models/JournalDtoListEnvelope';
export type { JournalEntryCreateDto } from './models/JournalEntryCreateDto';
export type { JournalEntryDto } from './models/JournalEntryDto';
export type { JournalEntryDtoListEnvelope } from './models/JournalEntryDtoListEnvelope';
export type { JournalEntryUpdateDto } from './models/JournalEntryUpdateDto';
export type { JournalTypeCreateDto } from './models/JournalTypeCreateDto';
export type { JournalTypeDto } from './models/JournalTypeDto';
export type { JournalTypeDtoEnvelope } from './models/JournalTypeDtoEnvelope';
export type { JournalTypeDtoListEnvelope } from './models/JournalTypeDtoListEnvelope';
export type { JournalTypeUpdateDto } from './models/JournalTypeUpdateDto';
export type { JournalUpdateDto } from './models/JournalUpdateDto';
export type { LedgerDto } from './models/LedgerDto';
export type { LedgerDtoEnvelope } from './models/LedgerDtoEnvelope';
export type { LedgerDtoListEnvelope } from './models/LedgerDtoListEnvelope';
export type { LoanApplicationCreateDto } from './models/LoanApplicationCreateDto';
export type { LoanApplicationDto } from './models/LoanApplicationDto';
export type { LoanApplicationDtoEnvelope } from './models/LoanApplicationDtoEnvelope';
export type { LoanApplicationDtoListEnvelope } from './models/LoanApplicationDtoListEnvelope';
export type { LoanApplicationUpdateDto } from './models/LoanApplicationUpdateDto';
export type { LoanCreateDto } from './models/LoanCreateDto';
export type { LoanDto } from './models/LoanDto';
export type { LoanDtoEnvelope } from './models/LoanDtoEnvelope';
export type { LoanDtoListEnvelope } from './models/LoanDtoListEnvelope';
export type { LoanUpdateDto } from './models/LoanUpdateDto';
export type { Money } from './models/Money';
export { Operation } from './models/Operation';
export type { PaymentCommissionCreateDto } from './models/PaymentCommissionCreateDto';
export type { PaymentCommissionDto } from './models/PaymentCommissionDto';
export type { PaymentCommissionDtoListEnvelope } from './models/PaymentCommissionDtoListEnvelope';
export type { PaymentCommissionUpdateDto } from './models/PaymentCommissionUpdateDto';
export { ReceiptCreateDto } from './models/ReceiptCreateDto';
export { ReceiptDto } from './models/ReceiptDto';
export type { ReceiptDtoEnvelope } from './models/ReceiptDtoEnvelope';
export type { ReceiptDtoListEnvelope } from './models/ReceiptDtoListEnvelope';
export type { ReceiptUpdateDto } from './models/ReceiptUpdateDto';
export type { ShareClassCreateDto } from './models/ShareClassCreateDto';
export type { ShareClassDto } from './models/ShareClassDto';
export type { ShareClassDtoEnvelope } from './models/ShareClassDtoEnvelope';
export type { ShareClassDtoListEnvelope } from './models/ShareClassDtoListEnvelope';
export type { ShareClassUpdateDto } from './models/ShareClassUpdateDto';
export type { ShareIssuanceCreateDto } from './models/ShareIssuanceCreateDto';
export type { ShareIssuanceDto } from './models/ShareIssuanceDto';
export type { ShareIssuanceDtoEnvelope } from './models/ShareIssuanceDtoEnvelope';
export type { ShareIssuanceDtoListEnvelope } from './models/ShareIssuanceDtoListEnvelope';
export type { ShareIssuanceUpdateDto } from './models/ShareIssuanceUpdateDto';
export type { ShareTransferCreateDto } from './models/ShareTransferCreateDto';
export type { ShareTransferDto } from './models/ShareTransferDto';
export type { ShareTransferDtoEnvelope } from './models/ShareTransferDtoEnvelope';
export type { ShareTransferDtoListEnvelope } from './models/ShareTransferDtoListEnvelope';
export type { ShareTransferReasonCreateDto } from './models/ShareTransferReasonCreateDto';
export type { ShareTransferReasonDto } from './models/ShareTransferReasonDto';
export type { ShareTransferReasonDtoEnvelope } from './models/ShareTransferReasonDtoEnvelope';
export type { ShareTransferReasonDtoListEnvelope } from './models/ShareTransferReasonDtoListEnvelope';
export type { ShareTransferReasonUpdateDto } from './models/ShareTransferReasonUpdateDto';
export type { ShareTransferUpdateDto } from './models/ShareTransferUpdateDto';
export type { TaxPolicyCreateDto } from './models/TaxPolicyCreateDto';
export type { TaxPolicyDto } from './models/TaxPolicyDto';
export type { TaxPolicyDtoEnvelope } from './models/TaxPolicyDtoEnvelope';
export type { TaxPolicyDtoListEnvelope } from './models/TaxPolicyDtoListEnvelope';
export type { TaxPolicyUpdateDto } from './models/TaxPolicyUpdateDto';
export type { TaxRateCreateDto } from './models/TaxRateCreateDto';
export type { TaxRateDto } from './models/TaxRateDto';
export type { TaxRateDtoEnvelope } from './models/TaxRateDtoEnvelope';
export type { TaxRateDtoListEnvelope } from './models/TaxRateDtoListEnvelope';
export type { TaxRateUpdateDto } from './models/TaxRateUpdateDto';
export type { TenantId } from './models/TenantId';
export type { TransactionCategoryCreateDto } from './models/TransactionCategoryCreateDto';
export type { TransactionCategoryDto } from './models/TransactionCategoryDto';
export type { TransactionCategoryDtoEnvelope } from './models/TransactionCategoryDtoEnvelope';
export type { TransactionCategoryDtoListEnvelope } from './models/TransactionCategoryDtoListEnvelope';
export type { TransactionCategoryUpdateDto } from './models/TransactionCategoryUpdateDto';
export type { TransactionCreateDto } from './models/TransactionCreateDto';
export type { TransactionDto } from './models/TransactionDto';
export type { TransactionDtoEnvelope } from './models/TransactionDtoEnvelope';
export type { TransactionDtoListEnvelope } from './models/TransactionDtoListEnvelope';
export type { TransactionUpdateDto } from './models/TransactionUpdateDto';
export type { UpdateLedgerDto } from './models/UpdateLedgerDto';

export { AccountGroupsService } from './services/AccountGroupsService';
export { AccountingPeriodsService } from './services/AccountingPeriodsService';
export { AccountsService } from './services/AccountsService';
export { BankingService } from './services/BankingService';
export { BillingProfilesService } from './services/BillingProfilesService';
export { BudgetsService } from './services/BudgetsService';
export { CommissionsService } from './services/CommissionsService';
export { CostCentresService } from './services/CostCentresService';
export { FinancialBooksService } from './services/FinancialBooksService';
export { FiscalsService } from './services/FiscalsService';
export { FiscalYearsService } from './services/FiscalYearsService';
export { GrantsService } from './services/GrantsService';
export { InvoiceEnumerationRangesService } from './services/InvoiceEnumerationRangesService';
export { JournalsService } from './services/JournalsService';
export { JournalTypesService } from './services/JournalTypesService';
export { LedgersService } from './services/LedgersService';
export { LoansService } from './services/LoansService';
export { ReceiptsService } from './services/ReceiptsService';
export { SharesService } from './services/SharesService';
export { TaxesService } from './services/TaxesService';
export { TransactionsService } from './services/TransactionsService';
