"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionsService = exports.TaxesService = exports.SharesService = exports.ReceiptsService = exports.LoansService = exports.LedgersService = exports.JournalTypesService = exports.JournalsService = exports.InvoiceEnumerationRangesService = exports.GrantsService = exports.FiscalYearsService = exports.FiscalsService = exports.FinancialBooksService = exports.CostCentresService = exports.CommissionsService = exports.BudgetsService = exports.BillingProfilesService = exports.BankingService = exports.AccountsService = exports.AccountingPeriodsService = exports.AccountGroupsService = exports.ReceiptDto = exports.ReceiptCreateDto = exports.Operation = exports.InvoiceEnumerationRangeUpdateDto = exports.InvoiceEnumerationRangeDto = exports.InvoiceEnumerationRangeCreateDto = exports.CostCentreUpdateDto = exports.CostCentreDto = exports.CostCentreCreateDto = exports.BudgetAccountEntryUpdateDto = exports.BudgetAccountEntryDto = exports.BudgetAccountEntryCreateDto = exports.BillingProfileDto = exports.BankGuaranteeUpdateDto = exports.BankGuaranteeDto = exports.BankGuaranteeCreateDto = exports.BankAccountUpdateDto = exports.BankAccountDto = exports.BankAccountCreateDto = exports.AccountUpdateDto = exports.AccountingEntryUpdateDto = exports.AccountingEntryDto = exports.AccountingEntryCreateDto = exports.AccountDto = exports.AccountCreateDto = exports.OpenAPI = exports.CancelError = exports.CancelablePromise = exports.ApiError = void 0;
/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var ApiError_1 = require("./core/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var CancelablePromise_1 = require("./core/CancelablePromise");
Object.defineProperty(exports, "CancelablePromise", { enumerable: true, get: function () { return CancelablePromise_1.CancelablePromise; } });
Object.defineProperty(exports, "CancelError", { enumerable: true, get: function () { return CancelablePromise_1.CancelError; } });
var OpenAPI_1 = require("./core/OpenAPI");
Object.defineProperty(exports, "OpenAPI", { enumerable: true, get: function () { return OpenAPI_1.OpenAPI; } });
var AccountCreateDto_1 = require("./models/AccountCreateDto");
Object.defineProperty(exports, "AccountCreateDto", { enumerable: true, get: function () { return AccountCreateDto_1.AccountCreateDto; } });
var AccountDto_1 = require("./models/AccountDto");
Object.defineProperty(exports, "AccountDto", { enumerable: true, get: function () { return AccountDto_1.AccountDto; } });
var AccountingEntryCreateDto_1 = require("./models/AccountingEntryCreateDto");
Object.defineProperty(exports, "AccountingEntryCreateDto", { enumerable: true, get: function () { return AccountingEntryCreateDto_1.AccountingEntryCreateDto; } });
var AccountingEntryDto_1 = require("./models/AccountingEntryDto");
Object.defineProperty(exports, "AccountingEntryDto", { enumerable: true, get: function () { return AccountingEntryDto_1.AccountingEntryDto; } });
var AccountingEntryUpdateDto_1 = require("./models/AccountingEntryUpdateDto");
Object.defineProperty(exports, "AccountingEntryUpdateDto", { enumerable: true, get: function () { return AccountingEntryUpdateDto_1.AccountingEntryUpdateDto; } });
var AccountUpdateDto_1 = require("./models/AccountUpdateDto");
Object.defineProperty(exports, "AccountUpdateDto", { enumerable: true, get: function () { return AccountUpdateDto_1.AccountUpdateDto; } });
var BankAccountCreateDto_1 = require("./models/BankAccountCreateDto");
Object.defineProperty(exports, "BankAccountCreateDto", { enumerable: true, get: function () { return BankAccountCreateDto_1.BankAccountCreateDto; } });
var BankAccountDto_1 = require("./models/BankAccountDto");
Object.defineProperty(exports, "BankAccountDto", { enumerable: true, get: function () { return BankAccountDto_1.BankAccountDto; } });
var BankAccountUpdateDto_1 = require("./models/BankAccountUpdateDto");
Object.defineProperty(exports, "BankAccountUpdateDto", { enumerable: true, get: function () { return BankAccountUpdateDto_1.BankAccountUpdateDto; } });
var BankGuaranteeCreateDto_1 = require("./models/BankGuaranteeCreateDto");
Object.defineProperty(exports, "BankGuaranteeCreateDto", { enumerable: true, get: function () { return BankGuaranteeCreateDto_1.BankGuaranteeCreateDto; } });
var BankGuaranteeDto_1 = require("./models/BankGuaranteeDto");
Object.defineProperty(exports, "BankGuaranteeDto", { enumerable: true, get: function () { return BankGuaranteeDto_1.BankGuaranteeDto; } });
var BankGuaranteeUpdateDto_1 = require("./models/BankGuaranteeUpdateDto");
Object.defineProperty(exports, "BankGuaranteeUpdateDto", { enumerable: true, get: function () { return BankGuaranteeUpdateDto_1.BankGuaranteeUpdateDto; } });
var BillingProfileDto_1 = require("./models/BillingProfileDto");
Object.defineProperty(exports, "BillingProfileDto", { enumerable: true, get: function () { return BillingProfileDto_1.BillingProfileDto; } });
var BudgetAccountEntryCreateDto_1 = require("./models/BudgetAccountEntryCreateDto");
Object.defineProperty(exports, "BudgetAccountEntryCreateDto", { enumerable: true, get: function () { return BudgetAccountEntryCreateDto_1.BudgetAccountEntryCreateDto; } });
var BudgetAccountEntryDto_1 = require("./models/BudgetAccountEntryDto");
Object.defineProperty(exports, "BudgetAccountEntryDto", { enumerable: true, get: function () { return BudgetAccountEntryDto_1.BudgetAccountEntryDto; } });
var BudgetAccountEntryUpdateDto_1 = require("./models/BudgetAccountEntryUpdateDto");
Object.defineProperty(exports, "BudgetAccountEntryUpdateDto", { enumerable: true, get: function () { return BudgetAccountEntryUpdateDto_1.BudgetAccountEntryUpdateDto; } });
var CostCentreCreateDto_1 = require("./models/CostCentreCreateDto");
Object.defineProperty(exports, "CostCentreCreateDto", { enumerable: true, get: function () { return CostCentreCreateDto_1.CostCentreCreateDto; } });
var CostCentreDto_1 = require("./models/CostCentreDto");
Object.defineProperty(exports, "CostCentreDto", { enumerable: true, get: function () { return CostCentreDto_1.CostCentreDto; } });
var CostCentreUpdateDto_1 = require("./models/CostCentreUpdateDto");
Object.defineProperty(exports, "CostCentreUpdateDto", { enumerable: true, get: function () { return CostCentreUpdateDto_1.CostCentreUpdateDto; } });
var InvoiceEnumerationRangeCreateDto_1 = require("./models/InvoiceEnumerationRangeCreateDto");
Object.defineProperty(exports, "InvoiceEnumerationRangeCreateDto", { enumerable: true, get: function () { return InvoiceEnumerationRangeCreateDto_1.InvoiceEnumerationRangeCreateDto; } });
var InvoiceEnumerationRangeDto_1 = require("./models/InvoiceEnumerationRangeDto");
Object.defineProperty(exports, "InvoiceEnumerationRangeDto", { enumerable: true, get: function () { return InvoiceEnumerationRangeDto_1.InvoiceEnumerationRangeDto; } });
var InvoiceEnumerationRangeUpdateDto_1 = require("./models/InvoiceEnumerationRangeUpdateDto");
Object.defineProperty(exports, "InvoiceEnumerationRangeUpdateDto", { enumerable: true, get: function () { return InvoiceEnumerationRangeUpdateDto_1.InvoiceEnumerationRangeUpdateDto; } });
var Operation_1 = require("./models/Operation");
Object.defineProperty(exports, "Operation", { enumerable: true, get: function () { return Operation_1.Operation; } });
var ReceiptCreateDto_1 = require("./models/ReceiptCreateDto");
Object.defineProperty(exports, "ReceiptCreateDto", { enumerable: true, get: function () { return ReceiptCreateDto_1.ReceiptCreateDto; } });
var ReceiptDto_1 = require("./models/ReceiptDto");
Object.defineProperty(exports, "ReceiptDto", { enumerable: true, get: function () { return ReceiptDto_1.ReceiptDto; } });
var AccountGroupsService_1 = require("./services/AccountGroupsService");
Object.defineProperty(exports, "AccountGroupsService", { enumerable: true, get: function () { return AccountGroupsService_1.AccountGroupsService; } });
var AccountingPeriodsService_1 = require("./services/AccountingPeriodsService");
Object.defineProperty(exports, "AccountingPeriodsService", { enumerable: true, get: function () { return AccountingPeriodsService_1.AccountingPeriodsService; } });
var AccountsService_1 = require("./services/AccountsService");
Object.defineProperty(exports, "AccountsService", { enumerable: true, get: function () { return AccountsService_1.AccountsService; } });
var BankingService_1 = require("./services/BankingService");
Object.defineProperty(exports, "BankingService", { enumerable: true, get: function () { return BankingService_1.BankingService; } });
var BillingProfilesService_1 = require("./services/BillingProfilesService");
Object.defineProperty(exports, "BillingProfilesService", { enumerable: true, get: function () { return BillingProfilesService_1.BillingProfilesService; } });
var BudgetsService_1 = require("./services/BudgetsService");
Object.defineProperty(exports, "BudgetsService", { enumerable: true, get: function () { return BudgetsService_1.BudgetsService; } });
var CommissionsService_1 = require("./services/CommissionsService");
Object.defineProperty(exports, "CommissionsService", { enumerable: true, get: function () { return CommissionsService_1.CommissionsService; } });
var CostCentresService_1 = require("./services/CostCentresService");
Object.defineProperty(exports, "CostCentresService", { enumerable: true, get: function () { return CostCentresService_1.CostCentresService; } });
var FinancialBooksService_1 = require("./services/FinancialBooksService");
Object.defineProperty(exports, "FinancialBooksService", { enumerable: true, get: function () { return FinancialBooksService_1.FinancialBooksService; } });
var FiscalsService_1 = require("./services/FiscalsService");
Object.defineProperty(exports, "FiscalsService", { enumerable: true, get: function () { return FiscalsService_1.FiscalsService; } });
var FiscalYearsService_1 = require("./services/FiscalYearsService");
Object.defineProperty(exports, "FiscalYearsService", { enumerable: true, get: function () { return FiscalYearsService_1.FiscalYearsService; } });
var GrantsService_1 = require("./services/GrantsService");
Object.defineProperty(exports, "GrantsService", { enumerable: true, get: function () { return GrantsService_1.GrantsService; } });
var InvoiceEnumerationRangesService_1 = require("./services/InvoiceEnumerationRangesService");
Object.defineProperty(exports, "InvoiceEnumerationRangesService", { enumerable: true, get: function () { return InvoiceEnumerationRangesService_1.InvoiceEnumerationRangesService; } });
var JournalsService_1 = require("./services/JournalsService");
Object.defineProperty(exports, "JournalsService", { enumerable: true, get: function () { return JournalsService_1.JournalsService; } });
var JournalTypesService_1 = require("./services/JournalTypesService");
Object.defineProperty(exports, "JournalTypesService", { enumerable: true, get: function () { return JournalTypesService_1.JournalTypesService; } });
var LedgersService_1 = require("./services/LedgersService");
Object.defineProperty(exports, "LedgersService", { enumerable: true, get: function () { return LedgersService_1.LedgersService; } });
var LoansService_1 = require("./services/LoansService");
Object.defineProperty(exports, "LoansService", { enumerable: true, get: function () { return LoansService_1.LoansService; } });
var ReceiptsService_1 = require("./services/ReceiptsService");
Object.defineProperty(exports, "ReceiptsService", { enumerable: true, get: function () { return ReceiptsService_1.ReceiptsService; } });
var SharesService_1 = require("./services/SharesService");
Object.defineProperty(exports, "SharesService", { enumerable: true, get: function () { return SharesService_1.SharesService; } });
var TaxesService_1 = require("./services/TaxesService");
Object.defineProperty(exports, "TaxesService", { enumerable: true, get: function () { return TaxesService_1.TaxesService; } });
var TransactionsService_1 = require("./services/TransactionsService");
Object.defineProperty(exports, "TransactionsService", { enumerable: true, get: function () { return TransactionsService_1.TransactionsService; } });
