/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/version": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/health": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/hello": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/register": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
          };
        };
      };
    };
  };
  "/login": {
    post: {
      parameters: {
        query?: {
          useCookies?: boolean;
          useSessionCookies?: boolean;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["AccessTokenResponse"];
          };
        };
      };
    };
  };
  "/refresh": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RefreshRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["AccessTokenResponse"];
          };
        };
      };
    };
  };
  "/confirmEmail": {
    get: operations["MapIdentityApi-/confirmEmail"];
  };
  "/resendConfirmationEmail": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ResendConfirmationEmailRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/forgotPassword": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ForgotPasswordRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
          };
        };
      };
    };
  };
  "/resetPassword": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ResetPasswordRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
          };
        };
      };
    };
  };
  "/manage/2fa": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["TwoFactorRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["TwoFactorResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
          };
        };
        /** @description Not Found */
        404: {
          content: never;
        };
      };
    };
  };
  "/manage/info": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["InfoResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
          };
        };
        /** @description Not Found */
        404: {
          content: never;
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["InfoRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["InfoResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
          };
        };
        /** @description Not Found */
        404: {
          content: never;
        };
      };
    };
  };
  "/Account/PerformExternalLogin": {
    post: {
      requestBody?: {
        content: {
          "multipart/form-data": {
            provider?: string;
            returnUrl?: string;
          };
          "application/x-www-form-urlencoded": {
            provider?: string;
            returnUrl?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/Account/Logout": {
    post: {
      requestBody?: {
        content: {
          "multipart/form-data": {
            returnUrl?: string;
          };
          "application/x-www-form-urlencoded": {
            returnUrl?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/Account/Manage/LinkExternalLogin": {
    post: {
      requestBody?: {
        content: {
          "multipart/form-data": {
            provider?: string;
          };
          "application/x-www-form-urlencoded": {
            provider?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/Account/Manage/DownloadPersonalData": {
    post: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v2/LogisticsService/Stock": {
    /**
     * Get all stock-related contacts
     * @description Retrieves all business-owned contacts related to stock and logistics for the specified tenant.
     */
    get: operations["GetContactsAsync"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AccessTokenResponse: {
      tokenType?: string | null;
      accessToken: string | null;
      /** Format: int64 */
      expiresIn: number;
      refreshToken: string | null;
    };
    ContactDto: {
      id?: string | null;
      /** Format: date-time */
      timestamp?: string | null;
      qualifiedName?: string | null;
      tenantId?: string | null;
      /** @enum {string} */
      type?: "Individual" | "Organization";
      /** Format: email */
      email?: string | null;
      /** Format: tel */
      phone?: string | null;
      publicName?: string | null;
      firstName?: string | null;
      lastName?: string | null;
      jobTitle?: string | null;
      coverUrl?: string | null;
      avatarUrl?: string | null;
      countryId?: string | null;
      timezoneId?: string | null;
      languageId?: string | null;
      socialProfileId?: string | null;
      /** Format: uri */
      webUrl?: string | null;
      /** Format: uri */
      gitHubUrl?: string | null;
      /** Format: uri */
      twitchUrl?: string | null;
      /** Format: uri */
      redditUrl?: string | null;
      /** Format: uri */
      tikTokUrl?: string | null;
      /** Format: uri */
      websiteUrl?: string | null;
      /** Format: uri */
      twitterUrl?: string | null;
      /** Format: uri */
      facebookUrl?: string | null;
      /** Format: uri */
      youTubeUrl?: string | null;
      /** Format: uri */
      linkedInUrl?: string | null;
      /** Format: uri */
      instagramUrl?: string | null;
      githubUsername?: string | null;
      duns?: string | null;
      taxId?: string | null;
      about?: string | null;
      street?: string | null;
      cartId?: string | null;
      cityId?: string | null;
      zipCode?: string | null;
      stateId?: string | null;
      walletId?: string | null;
      faxNumber?: string | null;
      postalCode?: string | null;
      currencyId?: string | null;
      streetLine1?: string | null;
      streetLine2?: string | null;
      territoryId?: string | null;
      mobilePhone?: string | null;
      enrollmentId?: string | null;
      annualRevenue?: string | null;
      relatedUserId?: string | null;
      businessPhone?: string | null;
      ownerContactId?: string | null;
      relatedTenantId?: string | null;
      activityFeedId?: string | null;
      parentContactId?: string | null;
      identityProvider?: string | null;
      partnerProfileId?: string | null;
      primaryContactId?: string | null;
      activeDirectoryId?: string | null;
      identityProviderAccessToken?: string | null;
      /** Format: date-time */
      birthday?: string | null;
    };
    ContactDtoListEnvelope: {
      isSuccess?: boolean;
      errorMessage?: string | null;
      correlationId?: string | null;
      /** Format: date-time */
      timestamp?: string;
      activityId?: string | null;
      result?: components["schemas"]["ContactDto"][] | null;
    };
    ErrorEnvelope: {
      isSuccess?: boolean;
      errorMessage?: string | null;
      correlationId?: string | null;
      /** Format: date-time */
      timestamp?: string;
      activityId?: string | null;
    };
    ForgotPasswordRequest: {
      email: string | null;
    };
    HttpValidationProblemDetails: {
      type?: string | null;
      title?: string | null;
      /** Format: int32 */
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
      errors?: {
        [key: string]: string[];
      } | null;
      [key: string]: unknown;
    };
    InfoRequest: {
      newEmail?: string | null;
      newPassword?: string | null;
      oldPassword?: string | null;
    };
    InfoResponse: {
      email: string | null;
      isEmailConfirmed: boolean;
    };
    LoginRequest: {
      email: string | null;
      password: string | null;
      twoFactorCode?: string | null;
      twoFactorRecoveryCode?: string | null;
    };
    RefreshRequest: {
      refreshToken: string | null;
    };
    RegisterRequest: {
      email: string | null;
      password: string | null;
    };
    ResendConfirmationEmailRequest: {
      email: string | null;
    };
    ResetPasswordRequest: {
      email: string | null;
      resetCode: string | null;
      newPassword: string | null;
    };
    TwoFactorRequest: {
      enable?: boolean | null;
      twoFactorCode?: string | null;
      resetSharedKey?: boolean;
      resetRecoveryCodes?: boolean;
      forgetMachine?: boolean;
    };
    TwoFactorResponse: {
      sharedKey: string | null;
      /** Format: int32 */
      recoveryCodesLeft: number;
      recoveryCodes?: string[] | null;
      isTwoFactorEnabled: boolean;
      isMachineRemembered: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  "MapIdentityApi-/confirmEmail": {
    parameters: {
      query: {
        userId: string;
        code: string;
        changedEmail?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /**
   * Get all stock-related contacts
   * @description Retrieves all business-owned contacts related to stock and logistics for the specified tenant.
   */
  GetContactsAsync: {
    parameters: {
      query: {
        tenantId: string;
        "api-version"?: string;
      };
      header?: {
        "x-api-version"?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ContactDtoListEnvelope"];
          "application/xml": components["schemas"]["ContactDtoListEnvelope"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
          "application/xml": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
          "application/xml": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
}
