/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type WebPageDto = {
    id?: string | null;
    timestamp?: string | null;
    order?: number;
    slug?: string | null;
    name?: string | null;
    title?: string | null;
    excerpt?: string | null;
    password?: string | null;
    description?: string | null;
    highlightImage?: string | null;
    canonicalUrl?: string | null;
    seoTitle?: string | null;
    seoKeyWords?: string | null;
    seoKeyPhrases?: string | null;
    metaDescription?: string | null;
    twitterImage?: string | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    facebookImage?: string | null;
    facebookTitle?: string | null;
    facebookDescription?: string | null;
    featuredImageUrl?: string | null;
    content?: string | null;
    code?: string | null;
    namespace?: string | null;
    typeName?: string | null;
    generatedCode?: string | null;
    compilationPath?: string | null;
    htmlContent?: string | null;
    cSharpContent?: string | null;
    razorContent?: string | null;
    cssContent?: string | null;
    jsContent?: string | null;
    cssFiles?: string | null;
    jsFiles?: string | null;
    razorGeneratedCode?: string | null;
    cSharpGeneratedCode?: string | null;
    template?: boolean;
    default?: boolean;
    enable?: boolean;
    enableComments?: boolean;
    displaySocialBox?: boolean;
    published?: boolean;
    inTrashCan?: boolean;
    systemLocked?: boolean;
    allowPingBacks?: boolean;
    allowTrackbacks?: boolean;
    cornerstoneContent?: boolean;
    isEssentialContent?: boolean;
    allowSearchEngineIndexing?: boolean;
    tenantId?: string | null;
    webPortalId?: string | null;
    websiteThemeId?: string | null;
    enrollmentId?: string | null;
    socialProfileId?: string | null;
    parentWebContentId?: string | null;
    parentWebContentVersionId?: string | null;
    webTemplateID?: string | null;
    isHomePage?: boolean;
    isStorePage?: boolean;
    isCartPage?: boolean;
    isBlogPage?: boolean;
    isAccountPage?: boolean;
    isCheckoutPage?: boolean;
    isWishListsPage?: boolean;
    isContactPage?: boolean;
    isPrivacyPolicyPage?: boolean;
    isTermsOfServicePage?: boolean;
};

