/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type CatalogItemUpdateDto = {
    hot?: boolean;
    sku?: string | null;
    upc?: string | null;
    ean?: string | null;
    mpn?: string | null;
    skUs?: string | null;
    isbn?: string | null;
    upCs?: string | null;
    eaNs?: string | null;
    asin?: string | null;
    gtin?: string | null;
    mpNs?: string | null;
    part?: string | null;
    name?: string | null;
    onSale?: boolean;
    isbNs?: string | null;
    asiNs?: string | null;
    gtiNs?: string | null;
    width?: number;
    model?: string | null;
    auction?: boolean;
    title?: string | null;
    color?: string | null;
    deleted?: boolean;
    digital?: boolean;
    preSale?: boolean;
    taxable?: boolean;
    inStock?: boolean;
    isbN13?: string | null;
    unspsc?: string | null;
    weight?: number;
    length?: number;
    height?: number;
    unitId?: string | null;
    series?: string | null;
    featured?: boolean;
    brands?: string | null;
    trending?: boolean;
    lowStock?: boolean;
    barcode?: string | null;
    unspsCs?: string | null;
    pattern?: string | null;
    published?: boolean;
    byRequest?: boolean;
    summary?: string | null;
    brandId?: string | null;
    viewsCount?: number;
    features?: string | null;
    material?: string | null;
    onDiscount?: boolean;
    totalTax?: number;
    tenantId?: string | null;
    permalink?: string | null;
    brandName?: string | null;
    reviewsCount?: number;
    isDailyDeal?: boolean;
    languageId?: string | null;
    categories?: string | null;
    finalPrice?: number;
    itemTypeId?: string | null;
    categoryId?: string | null;
    currencyId?: string | null;
    reviewsAvg?: number;
    isNewArrival?: boolean;
    isWeeklyDeal?: boolean;
    isBestSeller?: boolean;
    unitGroupId?: string | null;
    description?: string | null;
    ingredients?: string | null;
    releaseDate?: string | null;
    isMonthlyDeal?: boolean;
    recurrency?: number;
    paymentCost?: number;
    customTaxValue?: number;
    hasVariations?: boolean;
    questionsCount?: number;
    enrollmentId?: string | null;
    supplierCode?: string | null;
    auctionEnd?: string;
    purchaseNote?: string | null;
    shipsToRules?: string | null;
    regularPrice?: number;
    images?: Array<string> | null;
    shippingCost?: number;
    parentItemId?: string | null;
    itemTypeName?: string | null;
    cartRecordId?: string | null;
    variations?: Array<string> | null;
    tariffHeading?: string | null;
    packagedQuantity?: number;
    isFixedDiscount?: boolean;
    discountPrice?: number;
    isDealersChoice?: boolean;
    currentStock?: number;
    manageInventory?: boolean;
    auctionStart?: string;
    nutritionFacts?: string | null;
    mozaicCoverUrl?: string | null;
    packageContent?: string | null;
    discountAmount?: number;
    youtubeVideoId?: string | null;
    inCartQuantity?: number;
    isOfficialChoice?: boolean;
    publishedDate?: string;
    primaryImageUrl?: string | null;
    validPrimaryImage?: boolean;
    customTaxAmount?: number;
    longDescription?: string | null;
    compareRecordId?: string | null;
    measurementUnit?: string | null;
    shortDescription?: string | null;
    googleCategories?: string | null;
    isDeadlineDiscount?: boolean;
    displayShowcaseTab?: boolean;
    taxIncludedInPrice?: boolean;
    isProductOfTheWeek?: boolean;
    supplierProfileId?: string | null;
    shippingCountryId?: string | null;
    isProductOfTheMonth?: boolean;
    systemRequirements?: string | null;
    isPorcentualDiscount?: boolean;
    discountPercentage?: number;
    discountDeadLine?: string;
    displayOnGlobalMozaic?: boolean;
    displayOnBrandsMozaic?: boolean;
    customTaxPercentage?: number;
    estimatedTaxesInUsd?: number;
    customTaxDescription?: string | null;
    disableDefaultPolicies?: boolean;
    estimatedProfitInUsd?: number;
    displayOnCategoryMozaic?: boolean;
    officialDescriptionUrl?: string | null;
    energyEfficiencyRating?: string | null;
    pageCoverBackgroundUrl?: string | null;
    estimatedBasePriceInUsd?: number;
    estimatedDiscountsInUsd?: number;
    operatingSystemSupported?: string | null;
    estimatedSurchargesInUsd?: number;
    deadlineDiscountDueDate?: string | null;
    deadlineDiscountFromDate?: string | null;
    estimatedRegularPriceInUsd?: number;
    estimatedTaxBasePriceInUsd?: number;
    displayOnBannerMarketingRotation?: boolean;
    lastFixedPricesUpdateDateTime?: string | null;
    estimatedWitholdingTaxesInUsd?: number;
    estimatedPaymentCostInUsd?: number;
    estimatedPaymentTaxInUsd?: number;
    estimatedDefaultShippingCostInUsd?: number;
    estimatedDefaultShippingTaxInUsd?: number;
    estimatedTotalPriceInUsd?: number;
    recentlyViewedRecordId?: string | null;
    displayDescriptionEditor?: boolean;
    primaryGoogleCategoryId?: string | null;
    supportedOperatingSystem?: string | null;
    estimatedDealSavingsInUsd?: number;
    primaryGoogleCategoryName?: string | null;
    displayShortDescriptionEditor?: boolean;
    estimatedWithholdingTaxesInUsd?: number;
    selectedTags?: Array<string> | null;
    selectedTypes?: Array<string> | null;
    selectedBrands?: Array<string> | null;
    selectedCategories?: Array<string> | null;
    selectedTaxPolicies?: Array<string> | null;
    selectedPricingRules?: Array<string> | null;
    selectedRefundPolicies?: Array<string> | null;
    selectedReturnPolicies?: Array<string> | null;
    selectedPricingPolicies?: Array<string> | null;
    selectedGoogleCategories?: Array<string> | null;
    selectedWarrantyPolicies?: Array<string> | null;
    selectedShipmentPolicies?: Array<string> | null;
    selectedAttributesOptions?: Array<string> | null;
    selectedSellingMarginPolicies?: Array<string> | null;
};

