/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type CatalogItemCreateDto = {
    readonly id?: string;
    readonly timestamp?: string;
    sku?: string | null;
    upc?: string | null;
    ean?: string | null;
    mpn?: string | null;
    isbn?: string | null;
    asin?: string | null;
    gtin?: string | null;
    skUs?: string | null;
    upCs?: string | null;
    eaNs?: string | null;
    part?: string | null;
    name?: string | null;
    type?: string | null;
    mpNs?: string | null;
    isbNs?: string | null;
    asiNs?: string | null;
    gtiNs?: string | null;
    model?: string | null;
    title?: string | null;
    color?: string | null;
    unspsc?: string | null;
    unitId?: string | null;
    series?: string | null;
    barcode?: string | null;
    unspsCs?: string | null;
    summary?: string | null;
    brandId?: string | null;
    pattern?: string | null;
    features?: string | null;
    material?: string | null;
    tenantId?: string | null;
    permalink?: string | null;
    brandName?: string | null;
    variations?: string | null;
    categories?: string | null;
    languageId?: string | null;
    itemTypeId?: string | null;
    categoryId?: string | null;
    currencyId?: string | null;
    unitGroupId?: string | null;
    description?: string | null;
    ingredients?: string | null;
    supplierCode?: string | null;
    shipsToRules?: string | null;
    parentItemId?: string | null;
    purchaseNote?: string | null;
    tariffHeading?: string | null;
    mozaicCoverURL?: string | null;
    youtubeVideoId?: string | null;
    nutritionFacts?: string | null;
    packageContent?: string | null;
    primaryImageUrl?: string | null;
    googleCategories?: string | null;
    shortDescription?: string | null;
    supplierProfileId?: string | null;
    shippingCountryId?: string | null;
    systemRequirements?: string | null;
    customTaxDescription?: string | null;
    pageCoverBackgroundUrl?: string | null;
    officialDescriptionUrl?: string | null;
    recentlyViewedRecordId?: string | null;
    primaryGoogleCategoryId?: string | null;
    supportedOperatingSystem?: string | null;
    primaryGoogleCategoryName?: string | null;
    hot?: boolean;
    onSale?: boolean;
    auction?: boolean;
    deleted?: boolean;
    digital?: boolean;
    preSale?: boolean;
    taxable?: boolean;
    inStock?: boolean;
    trending?: boolean;
    featured?: boolean;
    lowStock?: boolean;
    published?: boolean;
    byRequest?: boolean;
    onDiscount?: boolean;
    isDailyDeal?: boolean;
    isNewArrival?: boolean;
    isWeeklyDeal?: boolean;
    isBestSeller?: boolean;
    isMonthlyDeal?: boolean;
    hasVariations?: boolean;
    isFixedDiscount?: boolean;
    manageInventory?: boolean;
    isDealersChoice?: boolean;
    isOfficialChoice?: boolean;
    validPrimaryImage?: boolean;
    isDeadlineDiscount?: boolean;
    taxIncludedInPrice?: boolean;
    displayShowcaseTab?: boolean;
    isProductOfTheWeek?: boolean;
    isProductOfTheMonth?: boolean;
    isPercentageDiscount?: boolean;
    displayOnGlobalMozaic?: boolean;
    displayOnBrandsMozaic?: boolean;
    disableDefaultPolicies?: boolean;
    displayOnCategoryMozaic?: boolean;
    displayDescriptionEditor?: boolean;
    displayShortDescriptionEditor?: boolean;
    displayOnBannerMarketingRotation?: boolean;
    viewsCount?: number;
    reviewsCount?: number;
    packagedQuantity?: number;
    recurrency?: number;
    currentStock?: number;
    customTaxValue?: number;
    width?: number;
    weight?: number;
    length?: number;
    height?: number;
    totalTax?: number;
    finalPrice?: number;
    reviewsAvg?: number;
    paymentCost?: number;
    regularPrice?: number;
    discountPrice?: number;
    discountAmount?: number;
    discountPercentage?: number;
    estimatedTaxesInUsd?: number;
    customTaxPercentage?: number;
    estimatedProfitInUsd?: number;
    estimatedBasePriceInUsd?: number;
    estimatedDiscountsInUsd?: number;
    estimatedSurchargesInUsd?: number;
    estimatedPaymentTaxInUsd?: number;
    estimatedTotalPriceInUsd?: number;
    estimatedPaymentCostInUsd?: number;
    estimatedDealSavingsInUsd?: number;
    estimatedRegularPriceInUsd?: number;
    estimatedTaxBasePriceInUsd?: number;
    estimatedWitholdingTaxesInUsd?: number;
    estimatedWithholdingTaxesInUsd?: number;
    estimatedDefaultShippingTaxInUsd?: number;
    estimatedDefaultShippingCostInUsd?: number;
    auctionEnd?: string | null;
    releaseDate?: string | null;
    auctionStart?: string | null;
    publishedDate?: string | null;
    discountDeadLine?: string | null;
    deadlineDiscountDueDate?: string | null;
    deadlineDiscountFromDate?: string | null;
    lastFixedPricesUpdateDateTime?: string | null;
    selectedTags?: Array<string> | null;
    selectedTypes?: Array<string> | null;
    selectedBrands?: Array<string> | null;
    selectedCategories?: Array<string> | null;
    selectedTaxPolicies?: Array<string> | null;
    selectedPricingRules?: Array<string> | null;
    selectedRefundPolicies?: Array<string> | null;
    selectedReturnPolicies?: Array<string> | null;
    selectedPricingPolicies?: Array<string> | null;
    selectedWarrantyPolicies?: Array<string> | null;
    selectedShipmentPolicies?: Array<string> | null;
    selectedGoogleCategories?: Array<string> | null;
    selectedAttributesOptions?: Array<string> | null;
    selectedSellingMarginPolicies?: Array<string> | null;
};

