// This file is auto-generated by @hey-api/openapi-ts

export type AccessTokenResponseReadable = {
    readonly tokenType?: string | null;
    accessToken: string | null;
    expiresIn: number;
    refreshToken: string | null;
};

export type AccessTokenResponseWritable = {
    accessToken: string | null;
    expiresIn: number;
    refreshToken: string | null;
};

export type AddProductToCompareRequestReadable = {
    readonly id?: string | null;
    cartId?: string | null;
    itemId?: string | null;
};

export type AddProductToCompareRequestWritable = {
    cartId?: string | null;
    itemId?: string | null;
};

export type BooleanEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    readonly activityId?: string | null;
    result?: boolean;
};

export type BooleanEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    result?: boolean;
};

export type CartDto = {
    id?: string | null;
    ip?: string | null;
    type?: string | null;
    total?: number;
    taxes?: number;
    freight?: number;
    subTotal?: number;
    currencyId?: string | null;
    countryId?: string | null;
    itemCartRecordsCount?: number | null;
    itemToCompareRecordsCount?: number | null;
};

export type CartDtoEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    readonly activityId?: string | null;
    result?: CartDto;
};

export type CartDtoEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    result?: CartDto;
};

export type CartUpdateRequest = {
    currencyId?: string | null;
    countryId?: string | null;
};

export type CountryDto = {
    id?: string | null;
    timestamp?: string | null;
    iso3?: string | null;
    iso2?: string | null;
    name?: string | null;
    nativeName?: string | null;
    flagUrl?: string | null;
};

export type CountryDtoEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    readonly activityId?: string | null;
    result?: CountryDto;
};

export type CountryDtoEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    result?: CountryDto;
};

export type CountrySwitchRequest = {
    cartId?: string | null;
    countryId?: string | null;
};

export type CurrencyDto = {
    id?: string | null;
    code?: string | null;
    name?: string | null;
    symbol?: string | null;
    country?: CountryDto;
};

export type CurrencyDtoEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    readonly activityId?: string | null;
    result?: CurrencyDto;
};

export type CurrencyDtoEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    result?: CurrencyDto;
};

export type CurrencyIdReadable = {
    readonly value?: string | null;
    code?: string | null;
    country?: string | null;
};

export type CurrencyIdWritable = {
    code?: string | null;
    country?: string | null;
};

export type CurrencySwitchRequest = {
    cartID?: string | null;
    currencyID?: string | null;
};

export type EmptyEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    readonly activityId?: string | null;
};

export type EmptyEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
};

export type ErrorEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    readonly activityId?: string | null;
};

export type ErrorEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
};

export type ForexRates = {
    success?: boolean;
    date?: string | null;
    base?: string | null;
    timestamp?: number;
    requestTimestamp?: string;
    rates?: {
        [key: string]: number;
    } | null;
};

export type ForgotPasswordRequest = {
    email: string | null;
};

export type HttpValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors?: {
        [key: string]: Array<string>;
    } | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | ({
        [key: string]: Array<string>;
    } | null) | undefined;
};

export type InfoRequest = {
    newEmail?: string | null;
    newPassword?: string | null;
    oldPassword?: string | null;
};

export type InfoResponse = {
    email: string | null;
    isEmailConfirmed: boolean;
};

export type ItemCartRecordCreateDto = {
    id?: string;
    timestamp?: string;
    cartId?: string | null;
    productId?: string | null;
    quantity?: number;
};

export type ItemCartRecordDtoReadable = {
    id?: string | null;
    timestamp?: string | null;
    closed?: boolean;
    itemId?: string | null;
    itemTitle?: string | null;
    itemShortDescription?: string | null;
    itemPrimaryImageUrl?: string | null;
    shippingPolicyId?: string | null;
    tenantId?: string | null;
    enrollmentId?: string | null;
    currencyId?: string | null;
    description?: string | null;
    quantity?: number;
    free?: boolean;
    freeReason?: string | null;
    freeReasonCode?: string | null;
    data?: string | null;
    dataLabel?: string | null;
    data1?: string | null;
    data1Label?: string | null;
    data2?: string | null;
    data2Label?: string | null;
    data3?: string | null;
    data3Label?: string | null;
    data4?: string | null;
    data4Label?: string | null;
    data5?: string | null;
    data5Label?: string | null;
    data6?: string | null;
    data6Label?: string | null;
    data7?: string | null;
    data7Label?: string | null;
    data8?: string | null;
    data8Label?: string | null;
    data9?: string | null;
    data9Label?: string | null;
    itemPriceId?: string | null;
    priceListItemId?: string | null;
    unitId?: string | null;
    unitGroupId?: string | null;
    taxCalculationMethod?: 'Included' | 'Excluded';
    costCalculationMethod?: 'Automatic' | 'Custom';
    forexRates?: ForexRates;
    forexRate?: number;
    totalDetailInUsd?: number;
    totalProfitInUsd?: number;
    totalDiscountsInUsd?: number;
    totalSurchargesInUsd?: number;
    totalTaxBaseInUsd?: number;
    totalTaxesInUsd?: number;
    totalWithheldTaxesInUsd?: number;
    totalShippingCostInUsd?: number;
    totalShippingTaxesInUsd?: number;
    totalWarrantyCostInUsd?: number;
    totalReturnCostInUsd?: number;
    totalRefundCostInUsd?: number;
    totalInUsd?: number;
    totalGlobalDiscountsInUsd?: number;
    totalGlobalSurchargesInUsd?: number;
    customGlobalSurchargesAmount?: number;
    customGlobalDiscountsAmount?: number;
    returnPolicyId?: string | null;
    refundPolicyId?: string | null;
    warrantyPolicyId?: string | null;
    shipmentPolicyId?: string | null;
    shippingLocationId?: string | null;
    locationId?: string | null;
    quoteItemRecordId?: string | null;
    businessProfileRecordId?: string | null;
    parentBillingItemRecordId?: string | null;
    currency?: CurrencyIdReadable;
    totalDetail?: number;
    totalDetailCurrencyId?: string | null;
    totalDetailAmount?: MoneyReadable;
    totalProfit?: number;
    totalProfitCurrencyId?: string | null;
    totalProfitAmount?: MoneyReadable;
    totalDiscounts?: number;
    totalDiscountsCurrencyId?: string | null;
    totalDiscountsAmount?: MoneyReadable;
    totalSurcharges?: number;
    totalSurchargesCurrencyId?: string | null;
    totalSurchargesAmount?: MoneyReadable;
    totalTaxBase?: number;
    totalTaxBaseCurrencyId?: string | null;
    totalTaxBaseAmount?: MoneyReadable;
    totalTaxes?: number;
    totalTaxesCurrencyId?: string | null;
    totalTaxesAmount?: MoneyReadable;
    totalShippingCost?: number;
    totalShippingCostCurrencyId?: string | null;
    totalShippingCostAmount?: MoneyReadable;
    totalShippingTax?: number;
    totalShippingTaxCurrencyId?: string | null;
    totalShippingTaxAmount?: MoneyReadable;
    totalWithheldTax?: number;
    totalWithheldTaxCurrencyId?: string | null;
    totalWithheldTaxAmount?: MoneyReadable;
    totalGlobalDiscounts?: number;
    totalGlobalDiscountsCurrencyId?: string | null;
    totalGlobalDiscountsAmount?: MoneyReadable;
    totalGlobalSurcharges?: number;
    totalGlobalSurchargesCurrencyId?: string | null;
    totalGlobalSurchargesAmount?: MoneyReadable;
    total?: number;
    totalCurrencyId?: string | null;
    totalAmount?: MoneyReadable;
    cartId?: string | null;
    itemID?: string | null;
    shippingAddressID?: string | null;
};

export type ItemCartRecordDtoWritable = {
    id?: string | null;
    timestamp?: string | null;
    closed?: boolean;
    itemId?: string | null;
    itemTitle?: string | null;
    itemShortDescription?: string | null;
    itemPrimaryImageUrl?: string | null;
    shippingPolicyId?: string | null;
    tenantId?: string | null;
    enrollmentId?: string | null;
    currencyId?: string | null;
    description?: string | null;
    quantity?: number;
    free?: boolean;
    freeReason?: string | null;
    freeReasonCode?: string | null;
    data?: string | null;
    dataLabel?: string | null;
    data1?: string | null;
    data1Label?: string | null;
    data2?: string | null;
    data2Label?: string | null;
    data3?: string | null;
    data3Label?: string | null;
    data4?: string | null;
    data4Label?: string | null;
    data5?: string | null;
    data5Label?: string | null;
    data6?: string | null;
    data6Label?: string | null;
    data7?: string | null;
    data7Label?: string | null;
    data8?: string | null;
    data8Label?: string | null;
    data9?: string | null;
    data9Label?: string | null;
    itemPriceId?: string | null;
    priceListItemId?: string | null;
    unitId?: string | null;
    unitGroupId?: string | null;
    taxCalculationMethod?: 'Included' | 'Excluded';
    costCalculationMethod?: 'Automatic' | 'Custom';
    forexRates?: ForexRates;
    forexRate?: number;
    totalDetailInUsd?: number;
    totalProfitInUsd?: number;
    totalDiscountsInUsd?: number;
    totalSurchargesInUsd?: number;
    totalTaxBaseInUsd?: number;
    totalTaxesInUsd?: number;
    totalWithheldTaxesInUsd?: number;
    totalShippingCostInUsd?: number;
    totalShippingTaxesInUsd?: number;
    totalWarrantyCostInUsd?: number;
    totalReturnCostInUsd?: number;
    totalRefundCostInUsd?: number;
    totalInUsd?: number;
    totalGlobalDiscountsInUsd?: number;
    totalGlobalSurchargesInUsd?: number;
    customGlobalSurchargesAmount?: number;
    customGlobalDiscountsAmount?: number;
    returnPolicyId?: string | null;
    refundPolicyId?: string | null;
    warrantyPolicyId?: string | null;
    shipmentPolicyId?: string | null;
    shippingLocationId?: string | null;
    locationId?: string | null;
    quoteItemRecordId?: string | null;
    businessProfileRecordId?: string | null;
    parentBillingItemRecordId?: string | null;
    currency?: CurrencyIdWritable;
    totalDetail?: number;
    totalDetailCurrencyId?: string | null;
    totalDetailAmount?: MoneyWritable;
    totalProfit?: number;
    totalProfitCurrencyId?: string | null;
    totalProfitAmount?: MoneyWritable;
    totalDiscounts?: number;
    totalDiscountsCurrencyId?: string | null;
    totalDiscountsAmount?: MoneyWritable;
    totalSurcharges?: number;
    totalSurchargesCurrencyId?: string | null;
    totalSurchargesAmount?: MoneyWritable;
    totalTaxBase?: number;
    totalTaxBaseCurrencyId?: string | null;
    totalTaxBaseAmount?: MoneyWritable;
    totalTaxes?: number;
    totalTaxesCurrencyId?: string | null;
    totalTaxesAmount?: MoneyWritable;
    totalShippingCost?: number;
    totalShippingCostCurrencyId?: string | null;
    totalShippingCostAmount?: MoneyWritable;
    totalShippingTax?: number;
    totalShippingTaxCurrencyId?: string | null;
    totalShippingTaxAmount?: MoneyWritable;
    totalWithheldTax?: number;
    totalWithheldTaxCurrencyId?: string | null;
    totalWithheldTaxAmount?: MoneyWritable;
    totalGlobalDiscounts?: number;
    totalGlobalDiscountsCurrencyId?: string | null;
    totalGlobalDiscountsAmount?: MoneyWritable;
    totalGlobalSurcharges?: number;
    totalGlobalSurchargesCurrencyId?: string | null;
    totalGlobalSurchargesAmount?: MoneyWritable;
    total?: number;
    totalCurrencyId?: string | null;
    totalAmount?: MoneyWritable;
    cartId?: string | null;
    itemID?: string | null;
    shippingAddressID?: string | null;
};

export type ItemCartRecordDtoEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    readonly activityId?: string | null;
    result?: ItemCartRecordDtoReadable;
};

export type ItemCartRecordDtoEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    result?: ItemCartRecordDtoWritable;
};

export type ItemCartRecordDtoListEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    readonly activityId?: string | null;
    result?: Array<ItemCartRecordDtoReadable> | null;
};

export type ItemCartRecordDtoListEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    result?: Array<ItemCartRecordDtoWritable> | null;
};

export type ItemCartRecordUpdateDto = {
    quantity?: number;
};

export type ItemToCompareCartRecordDto = {
    id?: string | null;
    timestamp?: string | null;
    cartId?: string | null;
    itemId?: string | null;
    itemTitle?: string | null;
    itemShortDescription?: string | null;
    itemPrimaryImageUrl?: string | null;
    brandId?: string | null;
    brandName?: string | null;
    categoryName?: string | null;
    categoryId?: string | null;
    googleCategoryId?: string | null;
    googleCategoryName?: string | null;
    totalTaxesInUsd?: number;
    totalPriceInUsd?: number;
    shippingCountryId?: string | null;
    tenantId?: string | null;
};

export type ItemToCompareCartRecordDtoEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    readonly activityId?: string | null;
    result?: ItemToCompareCartRecordDto;
};

export type ItemToCompareCartRecordDtoEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    result?: ItemToCompareCartRecordDto;
};

export type ItemToCompareCartRecordDtoListEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    readonly activityId?: string | null;
    result?: Array<ItemToCompareCartRecordDto> | null;
};

export type ItemToCompareCartRecordDtoListEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    result?: Array<ItemToCompareCartRecordDto> | null;
};

export type LoginRequest = {
    email: string | null;
    password: string | null;
    twoFactorCode?: string | null;
    twoFactorRecoveryCode?: string | null;
};

export type MoneyReadable = {
    amount?: number;
    currency?: CurrencyIdReadable;
};

export type MoneyWritable = {
    amount?: number;
    currency?: CurrencyIdWritable;
};

export type NewWishListRequest = {
    title?: string | null;
    description?: string | null;
    cartID?: string;
    public?: boolean;
};

export type ProductToWishListRequest = {
    wishListId?: string | null;
    itemId?: string | null;
};

export type RefreshRequest = {
    refreshToken: string | null;
};

export type RegisterRequest = {
    email: string | null;
    password: string | null;
};

export type ResendConfirmationEmailRequest = {
    email: string | null;
};

export type ResetPasswordRequest = {
    email: string | null;
    resetCode: string | null;
    newPassword: string | null;
};

export type TwoFactorRequest = {
    enable?: boolean | null;
    twoFactorCode?: string | null;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
};

export type TwoFactorResponse = {
    sharedKey: string | null;
    recoveryCodesLeft: number;
    recoveryCodes?: Array<string> | null;
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
};

export type WishListDto = {
    id?: string | null;
    timestamp?: string | null;
    title?: string | null;
    description?: string | null;
    cartId?: string | null;
    public?: boolean;
};

export type WishListDtoEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    readonly activityId?: string | null;
    result?: WishListDto;
};

export type WishListDtoEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    result?: WishListDto;
};

export type WishListItemRecordDto = {
    id?: string | null;
    timestamp?: string | null;
    wishListId?: string | null;
    productId?: string | null;
};

export type WishListUpdateDto = {
    title: string;
    description?: string | null;
    public?: boolean;
};

export type GetCartByIdAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}';
};

export type GetCartByIdAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCartByIdAsyncError = GetCartByIdAsyncErrors[keyof GetCartByIdAsyncErrors];

export type GetCartByIdAsyncResponses = {
    /**
     * OK
     */
    200: CartDtoEnvelopeReadable;
};

export type GetCartByIdAsyncResponse = GetCartByIdAsyncResponses[keyof GetCartByIdAsyncResponses];

export type UpdateCartAsyncData = {
    body?: CartUpdateRequest;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}';
};

export type UpdateCartAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type UpdateCartAsyncError = UpdateCartAsyncErrors[keyof UpdateCartAsyncErrors];

export type UpdateCartAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type UpdateCartAsyncResponse = UpdateCartAsyncResponses[keyof UpdateCartAsyncResponses];

export type GetCartCurrencyAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Currency';
};

export type GetCartCurrencyAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCartCurrencyAsyncError = GetCartCurrencyAsyncErrors[keyof GetCartCurrencyAsyncErrors];

export type GetCartCurrencyAsyncResponses = {
    /**
     * OK
     */
    200: CurrencyDtoEnvelopeReadable;
};

export type GetCartCurrencyAsyncResponse = GetCartCurrencyAsyncResponses[keyof GetCartCurrencyAsyncResponses];

export type SetCartCurrencyAsyncData = {
    body?: CurrencySwitchRequest;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Currency';
};

export type SetCartCurrencyAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type SetCartCurrencyAsyncError = SetCartCurrencyAsyncErrors[keyof SetCartCurrencyAsyncErrors];

export type SetCartCurrencyAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type SetCartCurrencyAsyncResponse = SetCartCurrencyAsyncResponses[keyof SetCartCurrencyAsyncResponses];

export type GetCartCountryAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Country';
};

export type GetCartCountryAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCartCountryAsyncError = GetCartCountryAsyncErrors[keyof GetCartCountryAsyncErrors];

export type GetCartCountryAsyncResponses = {
    /**
     * OK
     */
    200: CountryDtoEnvelopeReadable;
};

export type GetCartCountryAsyncResponse = GetCartCountryAsyncResponses[keyof GetCartCountryAsyncResponses];

export type SetCartCountryAsyncData = {
    body?: CountrySwitchRequest;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Country';
};

export type SetCartCountryAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type SetCartCountryAsyncError = SetCartCountryAsyncErrors[keyof SetCartCountryAsyncErrors];

export type SetCartCountryAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type SetCartCountryAsyncResponse = SetCartCountryAsyncResponses[keyof SetCartCountryAsyncResponses];

export type SubmitCartAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        tenantId?: string;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Submit';
};

export type SubmitCartAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type SubmitCartAsyncError = SubmitCartAsyncErrors[keyof SubmitCartAsyncErrors];

export type SubmitCartAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type SubmitCartAsyncResponse = SubmitCartAsyncResponses[keyof SubmitCartAsyncResponses];

export type GetActingCartData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/ActingCart';
};

export type GetActingCartErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetActingCartError = GetActingCartErrors[keyof GetActingCartErrors];

export type GetActingCartResponses = {
    /**
     * OK
     */
    200: CartDtoEnvelopeReadable;
};

export type GetActingCartResponse = GetActingCartResponses[keyof GetActingCartResponses];

export type GetGuestCartAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/GuestCart';
};

export type GetGuestCartAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetGuestCartAsyncError = GetGuestCartAsyncErrors[keyof GetGuestCartAsyncErrors];

export type GetGuestCartAsyncResponses = {
    /**
     * OK
     */
    200: CartDtoEnvelopeReadable;
};

export type GetGuestCartAsyncResponse = GetGuestCartAsyncResponses[keyof GetGuestCartAsyncResponses];

export type GetUserCartData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/UserCart';
};

export type GetUserCartErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetUserCartError = GetUserCartErrors[keyof GetUserCartErrors];

export type GetUserCartResponses = {
    /**
     * OK
     */
    200: CartDtoEnvelopeReadable;
};

export type GetUserCartResponse = GetUserCartResponses[keyof GetUserCartResponses];

export type GetTenantCartAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        tenantId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/BusinessCart/{tenantId}';
};

export type GetTenantCartAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetTenantCartAsyncError = GetTenantCartAsyncErrors[keyof GetTenantCartAsyncErrors];

export type GetTenantCartAsyncResponses = {
    /**
     * OK
     */
    200: CartDtoEnvelopeReadable;
};

export type GetTenantCartAsyncResponse = GetTenantCartAsyncResponses[keyof GetTenantCartAsyncResponses];

export type ClearCartRecordsData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Items';
};

export type ClearCartRecordsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type ClearCartRecordsError = ClearCartRecordsErrors[keyof ClearCartRecordsErrors];

export type ClearCartRecordsResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type ClearCartRecordsResponse = ClearCartRecordsResponses[keyof ClearCartRecordsResponses];

export type GetCartItemsData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Items';
};

export type GetCartItemsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCartItemsError = GetCartItemsErrors[keyof GetCartItemsErrors];

export type GetCartItemsResponses = {
    /**
     * OK
     */
    200: ItemCartRecordDtoListEnvelopeReadable;
};

export type GetCartItemsResponse = GetCartItemsResponses[keyof GetCartItemsResponses];

export type RemoveItemFromCartAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        itemId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Items/{itemId}';
};

export type RemoveItemFromCartAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type RemoveItemFromCartAsyncError = RemoveItemFromCartAsyncErrors[keyof RemoveItemFromCartAsyncErrors];

export type RemoveItemFromCartAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type RemoveItemFromCartAsyncResponse = RemoveItemFromCartAsyncResponses[keyof RemoveItemFromCartAsyncResponses];

export type AddItemToCartAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        itemId: string;
    };
    query?: {
        quantity?: number;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Items/{itemId}';
};

export type AddItemToCartAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type AddItemToCartAsyncError = AddItemToCartAsyncErrors[keyof AddItemToCartAsyncErrors];

export type AddItemToCartAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type AddItemToCartAsyncResponse = AddItemToCartAsyncResponses[keyof AddItemToCartAsyncResponses];

export type UpdateItemCartRecordAsyncData = {
    body?: ItemCartRecordUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        itemId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Items/{itemId}';
};

export type UpdateItemCartRecordAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type UpdateItemCartRecordAsyncError = UpdateItemCartRecordAsyncErrors[keyof UpdateItemCartRecordAsyncErrors];

export type UpdateItemCartRecordAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type UpdateItemCartRecordAsyncResponse = UpdateItemCartRecordAsyncResponses[keyof UpdateItemCartRecordAsyncResponses];

export type IsItemAlreadyInCartAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        itemId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Contains/{itemId}';
};

export type IsItemAlreadyInCartAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: EmptyEnvelopeReadable;
};

export type IsItemAlreadyInCartAsyncError = IsItemAlreadyInCartAsyncErrors[keyof IsItemAlreadyInCartAsyncErrors];

export type IsItemAlreadyInCartAsyncResponses = {
    /**
     * OK
     */
    200: BooleanEnvelopeReadable;
};

export type IsItemAlreadyInCartAsyncResponse = IsItemAlreadyInCartAsyncResponses[keyof IsItemAlreadyInCartAsyncResponses];

export type IncreaseItemCartRecordQuantityAsyncData = {
    body?: ItemCartRecordUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        itemId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Items/{itemId}/Increase';
};

export type IncreaseItemCartRecordQuantityAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type IncreaseItemCartRecordQuantityAsyncError = IncreaseItemCartRecordQuantityAsyncErrors[keyof IncreaseItemCartRecordQuantityAsyncErrors];

export type IncreaseItemCartRecordQuantityAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type IncreaseItemCartRecordQuantityAsyncResponse = IncreaseItemCartRecordQuantityAsyncResponses[keyof IncreaseItemCartRecordQuantityAsyncResponses];

export type DecreaseCartItemQuantityData = {
    body?: ItemCartRecordUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        itemId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Items/{itemId}/Decrease';
};

export type DecreaseCartItemQuantityErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type DecreaseCartItemQuantityError = DecreaseCartItemQuantityErrors[keyof DecreaseCartItemQuantityErrors];

export type DecreaseCartItemQuantityResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type DecreaseCartItemQuantityResponse = DecreaseCartItemQuantityResponses[keyof DecreaseCartItemQuantityResponses];

export type GetCartLinesAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Lines';
};

export type GetCartLinesAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCartLinesAsyncError = GetCartLinesAsyncErrors[keyof GetCartLinesAsyncErrors];

export type GetCartLinesAsyncResponses = {
    /**
     * OK
     */
    200: ItemCartRecordDtoListEnvelopeReadable;
};

export type GetCartLinesAsyncResponse = GetCartLinesAsyncResponses[keyof GetCartLinesAsyncResponses];

export type RemoveCartLineAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        lineId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Lines/{lineId}';
};

export type RemoveCartLineAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type RemoveCartLineAsyncError = RemoveCartLineAsyncErrors[keyof RemoveCartLineAsyncErrors];

export type RemoveCartLineAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type RemoveCartLineAsyncResponse = RemoveCartLineAsyncResponses[keyof RemoveCartLineAsyncResponses];

export type GetCartLineAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        lineId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Lines/{lineId}';
};

export type GetCartLineAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ItemCartRecordDtoEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCartLineAsyncError = GetCartLineAsyncErrors[keyof GetCartLineAsyncErrors];

export type GetCartLineAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type GetCartLineAsyncResponse = GetCartLineAsyncResponses[keyof GetCartLineAsyncResponses];

export type UpdateCartLineAsyncData = {
    body?: ItemCartRecordUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        lineId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Lines/{lineId}';
};

export type UpdateCartLineAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type UpdateCartLineAsyncError = UpdateCartLineAsyncErrors[keyof UpdateCartLineAsyncErrors];

export type UpdateCartLineAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type UpdateCartLineAsyncResponse = UpdateCartLineAsyncResponses[keyof UpdateCartLineAsyncResponses];

export type IncreaseCartLineAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        lineId: string;
    };
    query?: {
        quantity?: number;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Lines/{lineId}/Increase';
};

export type IncreaseCartLineAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type IncreaseCartLineAsyncError = IncreaseCartLineAsyncErrors[keyof IncreaseCartLineAsyncErrors];

export type IncreaseCartLineAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type IncreaseCartLineAsyncResponse = IncreaseCartLineAsyncResponses[keyof IncreaseCartLineAsyncResponses];

export type DecreaseCartLineAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        lineId: string;
    };
    query?: {
        quantity?: number;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Lines/{lineId}/Decrease';
};

export type DecreaseCartLineAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type DecreaseCartLineAsyncError = DecreaseCartLineAsyncErrors[keyof DecreaseCartLineAsyncErrors];

export type DecreaseCartLineAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type DecreaseCartLineAsyncResponse = DecreaseCartLineAsyncResponses[keyof DecreaseCartLineAsyncResponses];

export type GetCartWishListData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists';
};

export type GetCartWishListErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCartWishListError = GetCartWishListErrors[keyof GetCartWishListErrors];

export type GetCartWishListResponses = {
    /**
     * OK
     */
    200: Array<WishListDto>;
};

export type GetCartWishListResponse = GetCartWishListResponses[keyof GetCartWishListResponses];

export type CreateWishListAsyncData = {
    body?: NewWishListRequest;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists';
};

export type CreateWishListAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type CreateWishListAsyncError = CreateWishListAsyncErrors[keyof CreateWishListAsyncErrors];

export type CreateWishListAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type CreateWishListAsyncResponse = CreateWishListAsyncResponses[keyof CreateWishListAsyncResponses];

export type IsItemInWishListsData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        itemId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists/Contains/{itemId}';
};

export type IsItemInWishListsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type IsItemInWishListsError = IsItemInWishListsErrors[keyof IsItemInWishListsErrors];

export type IsItemInWishListsResponses = {
    /**
     * OK
     */
    200: BooleanEnvelopeReadable;
};

export type IsItemInWishListsResponse = IsItemInWishListsResponses[keyof IsItemInWishListsResponses];

export type WishListExistsAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        wishListId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists/{wishListId}/Exists';
};

export type WishListExistsAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type WishListExistsAsyncError = WishListExistsAsyncErrors[keyof WishListExistsAsyncErrors];

export type WishListExistsAsyncResponses = {
    /**
     * OK
     */
    200: BooleanEnvelopeReadable;
};

export type WishListExistsAsyncResponse = WishListExistsAsyncResponses[keyof WishListExistsAsyncResponses];

export type CartWishListExistsHeadData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        wishListId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists/{wishListId}/Exists';
};

export type CartWishListExistsHeadErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type CartWishListExistsHeadError = CartWishListExistsHeadErrors[keyof CartWishListExistsHeadErrors];

export type CartWishListExistsHeadResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type CartWishListExistsHeadResponse = CartWishListExistsHeadResponses[keyof CartWishListExistsHeadResponses];

export type DeleteCartWishListData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        wishListId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists/{wishListId}';
};

export type DeleteCartWishListErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type DeleteCartWishListError = DeleteCartWishListErrors[keyof DeleteCartWishListErrors];

export type DeleteCartWishListResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type DeleteCartWishListResponse = DeleteCartWishListResponses[keyof DeleteCartWishListResponses];

export type GetCartWishListDetailsData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        wishListId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists/{wishListId}';
};

export type GetCartWishListDetailsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCartWishListDetailsError = GetCartWishListDetailsErrors[keyof GetCartWishListDetailsErrors];

export type GetCartWishListDetailsResponses = {
    /**
     * OK
     */
    200: WishListDtoEnvelopeReadable;
};

export type GetCartWishListDetailsResponse = GetCartWishListDetailsResponses[keyof GetCartWishListDetailsResponses];

export type UpdateItemToWishListData = {
    body?: WishListUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        wishListId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists/{wishListId}';
};

export type UpdateItemToWishListErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type UpdateItemToWishListError = UpdateItemToWishListErrors[keyof UpdateItemToWishListErrors];

export type UpdateItemToWishListResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type UpdateItemToWishListResponse = UpdateItemToWishListResponses[keyof UpdateItemToWishListResponses];

export type GetCartWishListItemsData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        wishListId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists/{wishListId}/Records';
};

export type GetCartWishListItemsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCartWishListItemsError = GetCartWishListItemsErrors[keyof GetCartWishListItemsErrors];

export type GetCartWishListItemsResponses = {
    /**
     * OK
     */
    200: Array<WishListItemRecordDto>;
};

export type GetCartWishListItemsResponse = GetCartWishListItemsResponses[keyof GetCartWishListItemsResponses];

export type AddItemToWishListData = {
    body?: ProductToWishListRequest;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        wishListId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists/{wishListId}/Records';
};

export type AddItemToWishListErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type AddItemToWishListError = AddItemToWishListErrors[keyof AddItemToWishListErrors];

export type AddItemToWishListResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type AddItemToWishListResponse = AddItemToWishListResponses[keyof AddItemToWishListResponses];

export type DeleteCartWishListRecordData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        wishListId: string;
        recordId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists/{wishListId}/Records/{recordId}';
};

export type DeleteCartWishListRecordErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type DeleteCartWishListRecordError = DeleteCartWishListRecordErrors[keyof DeleteCartWishListRecordErrors];

export type DeleteCartWishListRecordResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type DeleteCartWishListRecordResponse = DeleteCartWishListRecordResponses[keyof DeleteCartWishListRecordResponses];

export type GetCartWishListItemAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        wishListId: string;
        recordId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/WishLists/{wishListId}/Records/{recordId}';
};

export type GetCartWishListItemAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCartWishListItemAsyncError = GetCartWishListItemAsyncErrors[keyof GetCartWishListItemAsyncErrors];

export type GetCartWishListItemAsyncResponses = {
    /**
     * OK
     */
    200: Array<WishListItemRecordDto>;
};

export type GetCartWishListItemAsyncResponse = GetCartWishListItemAsyncResponses[keyof GetCartWishListItemAsyncResponses];

export type GetCartCompareRecordsData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Compare';
};

export type GetCartCompareRecordsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCartCompareRecordsError = GetCartCompareRecordsErrors[keyof GetCartCompareRecordsErrors];

export type GetCartCompareRecordsResponses = {
    /**
     * OK
     */
    200: ItemToCompareCartRecordDtoListEnvelopeReadable;
};

export type GetCartCompareRecordsResponse = GetCartCompareRecordsResponses[keyof GetCartCompareRecordsResponses];

export type RemoveItemFromCompareTableAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        itemId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Compare/{itemId}';
};

export type RemoveItemFromCompareTableAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type RemoveItemFromCompareTableAsyncError = RemoveItemFromCompareTableAsyncErrors[keyof RemoveItemFromCompareTableAsyncErrors];

export type RemoveItemFromCompareTableAsyncResponses = {
    /**
     * OK
     */
    200: ItemToCompareCartRecordDto;
};

export type RemoveItemFromCompareTableAsyncResponse = RemoveItemFromCompareTableAsyncResponses[keyof RemoveItemFromCompareTableAsyncResponses];

export type GetCartCompareRecordData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        itemId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Compare/{itemId}';
};

export type GetCartCompareRecordErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCartCompareRecordError = GetCartCompareRecordErrors[keyof GetCartCompareRecordErrors];

export type GetCartCompareRecordResponses = {
    /**
     * OK
     */
    200: ItemToCompareCartRecordDtoEnvelopeReadable;
};

export type GetCartCompareRecordResponse = GetCartCompareRecordResponses[keyof GetCartCompareRecordResponses];

export type AddItemToCartCompareTableData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        itemId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Compare/{itemId}';
};

export type AddItemToCartCompareTableErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type AddItemToCartCompareTableError = AddItemToCartCompareTableErrors[keyof AddItemToCartCompareTableErrors];

export type AddItemToCartCompareTableResponses = {
    /**
     * OK
     */
    200: ItemCartRecordDtoReadable;
};

export type AddItemToCartCompareTableResponse = AddItemToCartCompareTableResponses[keyof AddItemToCartCompareTableResponses];

export type IsItemInCompareTableAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
        itemId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Carts/{cartId}/Compare/Contains/{itemId}';
};

export type IsItemInCompareTableAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type IsItemInCompareTableAsyncError = IsItemInCompareTableAsyncErrors[keyof IsItemInCompareTableAsyncErrors];

export type IsItemInCompareTableAsyncResponses = {
    /**
     * OK
     */
    200: BooleanEnvelopeReadable;
};

export type IsItemInCompareTableAsyncResponse = IsItemInCompareTableAsyncResponses[keyof IsItemInCompareTableAsyncResponses];

export type GetItemToCompareRecordsData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Compare/{cartId}';
};

export type GetItemToCompareRecordsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetItemToCompareRecordsError = GetItemToCompareRecordsErrors[keyof GetItemToCompareRecordsErrors];

export type GetItemToCompareRecordsResponses = {
    /**
     * OK
     */
    200: ItemToCompareCartRecordDtoListEnvelopeReadable;
};

export type GetItemToCompareRecordsResponse = GetItemToCompareRecordsResponses[keyof GetItemToCompareRecordsResponses];

export type GetItemToCompareRecordData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        recordId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Compare/{recordId}/Details';
};

export type GetItemToCompareRecordErrors = {
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetItemToCompareRecordError = GetItemToCompareRecordErrors[keyof GetItemToCompareRecordErrors];

export type GetItemToCompareRecordResponses = {
    /**
     * OK
     */
    200: ItemToCompareCartRecordDtoEnvelopeReadable;
};

export type GetItemToCompareRecordResponse = GetItemToCompareRecordResponses[keyof GetItemToCompareRecordResponses];

export type AddItemToCompareTableAsyncData = {
    body?: AddProductToCompareRequestWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Compare';
};

export type AddItemToCompareTableAsyncErrors = {
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type AddItemToCompareTableAsyncError = AddItemToCompareTableAsyncErrors[keyof AddItemToCompareTableAsyncErrors];

export type AddItemToCompareTableAsyncResponses = {
    /**
     * OK
     */
    200: ItemCartRecordDtoReadable;
};

export type AddItemToCompareTableAsyncResponse = AddItemToCompareTableAsyncResponses[keyof AddItemToCompareTableAsyncResponses];

export type RemoveItemFromCompareTableData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        recordId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Compare/{recordId}';
};

export type RemoveItemFromCompareTableErrors = {
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type RemoveItemFromCompareTableError = RemoveItemFromCompareTableErrors[keyof RemoveItemFromCompareTableErrors];

export type RemoveItemFromCompareTableResponses = {
    /**
     * OK
     */
    200: ItemToCompareCartRecordDto;
};

export type RemoveItemFromCompareTableResponse = RemoveItemFromCompareTableResponses[keyof RemoveItemFromCompareTableResponses];

export type GetVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/version';
};

export type GetVersionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hello';
};

export type GetHelloResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostRegisterError = PostRegisterErrors[keyof PostRegisterErrors];

export type PostRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostLoginData = {
    body: LoginRequest;
    path?: never;
    query?: {
        useCookies?: boolean;
        useSessionCookies?: boolean;
    };
    url: '/login';
};

export type PostLoginResponses = {
    /**
     * OK
     */
    200: AccessTokenResponseReadable;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/refresh';
};

export type PostRefreshResponses = {
    /**
     * OK
     */
    200: AccessTokenResponseReadable;
};

export type PostRefreshResponse = PostRefreshResponses[keyof PostRefreshResponses];

export type MapIdentityApiConfirmEmailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
        code: string;
        changedEmail?: string;
    };
    url: '/confirmEmail';
};

export type MapIdentityApiConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostResendConfirmationEmailData = {
    body: ResendConfirmationEmailRequest;
    path?: never;
    query?: never;
    url: '/resendConfirmationEmail';
};

export type PostResendConfirmationEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/forgotPassword';
};

export type PostForgotPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostForgotPasswordError = PostForgotPasswordErrors[keyof PostForgotPasswordErrors];

export type PostForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/resetPassword';
};

export type PostResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostResetPasswordError = PostResetPasswordErrors[keyof PostResetPasswordErrors];

export type PostResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostManage2FaData = {
    body: TwoFactorRequest;
    path?: never;
    query?: never;
    url: '/manage/2fa';
};

export type PostManage2FaErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostManage2FaError = PostManage2FaErrors[keyof PostManage2FaErrors];

export type PostManage2FaResponses = {
    /**
     * OK
     */
    200: TwoFactorResponse;
};

export type PostManage2FaResponse = PostManage2FaResponses[keyof PostManage2FaResponses];

export type GetManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type GetManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetManageInfoError = GetManageInfoErrors[keyof GetManageInfoErrors];

export type GetManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type GetManageInfoResponse = GetManageInfoResponses[keyof GetManageInfoResponses];

export type PostManageInfoData = {
    body: InfoRequest;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type PostManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostManageInfoError = PostManageInfoErrors[keyof PostManageInfoErrors];

export type PostManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type PostManageInfoResponse = PostManageInfoResponses[keyof PostManageInfoResponses];

export type AddItemToCartData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        cartId?: string;
        itemId?: string;
        quantity?: number;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Records/AddItem';
};

export type AddItemToCartErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type AddItemToCartError = AddItemToCartErrors[keyof AddItemToCartErrors];

export type AddItemToCartResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type AddItemToCartResponse = AddItemToCartResponses[keyof AddItemToCartResponses];

export type GetItemsInCartAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Records/{cartId}';
};

export type GetItemsInCartAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetItemsInCartAsyncError = GetItemsInCartAsyncErrors[keyof GetItemsInCartAsyncErrors];

export type GetItemsInCartAsyncResponses = {
    /**
     * OK
     */
    200: ItemCartRecordDtoListEnvelopeReadable;
};

export type GetItemsInCartAsyncResponse = GetItemsInCartAsyncResponses[keyof GetItemsInCartAsyncResponses];

export type RemoveProductFromCartByParamsData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        cartId?: string;
        productId?: string;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Records';
};

export type RemoveProductFromCartByParamsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type RemoveProductFromCartByParamsError = RemoveProductFromCartByParamsErrors[keyof RemoveProductFromCartByParamsErrors];

export type RemoveProductFromCartByParamsResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type RemoveProductFromCartByParamsResponse = RemoveProductFromCartByParamsResponses[keyof RemoveProductFromCartByParamsResponses];

export type AddProductToCartAsyncData = {
    body?: ItemCartRecordCreateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Records';
};

export type AddProductToCartAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type AddProductToCartAsyncError = AddProductToCartAsyncErrors[keyof AddProductToCartAsyncErrors];

export type AddProductToCartAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type AddProductToCartAsyncResponse = AddProductToCartAsyncResponses[keyof AddProductToCartAsyncResponses];

export type IsItemAlreadyInCartData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query: {
        itemID: string;
        cartID: string;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Records/IsInCart';
};

export type IsItemAlreadyInCartErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: EmptyEnvelopeReadable;
};

export type IsItemAlreadyInCartError = IsItemAlreadyInCartErrors[keyof IsItemAlreadyInCartErrors];

export type IsItemAlreadyInCartResponses = {
    /**
     * OK
     */
    200: BooleanEnvelopeReadable;
};

export type IsItemAlreadyInCartResponse = IsItemAlreadyInCartResponses[keyof IsItemAlreadyInCartResponses];

export type ClearCartAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query: {
        cartID: string;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Records/ClearCart';
};

export type ClearCartAsyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type ClearCartAsyncError = ClearCartAsyncErrors[keyof ClearCartAsyncErrors];

export type ClearCartAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type ClearCartAsyncResponse = ClearCartAsyncResponses[keyof ClearCartAsyncResponses];

export type GetItemCartRecordData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        recordId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Records/{recordId}/Details';
};

export type GetItemCartRecordErrors = {
    /**
     * Unauthorized
     */
    401: ItemCartRecordDtoEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetItemCartRecordError = GetItemCartRecordErrors[keyof GetItemCartRecordErrors];

export type GetItemCartRecordResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type GetItemCartRecordResponse = GetItemCartRecordResponses[keyof GetItemCartRecordResponses];

export type RemoveProductFromCartByRecordIdData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        recordId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Records/{recordId}';
};

export type RemoveProductFromCartByRecordIdErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type RemoveProductFromCartByRecordIdError = RemoveProductFromCartByRecordIdErrors[keyof RemoveProductFromCartByRecordIdErrors];

export type RemoveProductFromCartByRecordIdResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type RemoveProductFromCartByRecordIdResponse = RemoveProductFromCartByRecordIdResponses[keyof RemoveProductFromCartByRecordIdResponses];

export type UpdateItemCartRecordData = {
    body?: ItemCartRecordUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        recordId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Records/{recordId}';
};

export type UpdateItemCartRecordErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type UpdateItemCartRecordError = UpdateItemCartRecordErrors[keyof UpdateItemCartRecordErrors];

export type UpdateItemCartRecordResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type UpdateItemCartRecordResponse = UpdateItemCartRecordResponses[keyof UpdateItemCartRecordResponses];

export type IncreaseItemCartRecordData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        recordId: string;
    };
    query?: {
        quantity?: number;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Records/{recordId}/Increase';
};

export type IncreaseItemCartRecordErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type IncreaseItemCartRecordError = IncreaseItemCartRecordErrors[keyof IncreaseItemCartRecordErrors];

export type IncreaseItemCartRecordResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type IncreaseItemCartRecordResponse = IncreaseItemCartRecordResponses[keyof IncreaseItemCartRecordResponses];

export type DecreaseItemCartRecordData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        recordId: string;
    };
    query?: {
        quantity?: number;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/Records/{recordId}/Decrease';
};

export type DecreaseItemCartRecordErrors = {
    /**
     * Unauthorized
     */
    401: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type DecreaseItemCartRecordError = DecreaseItemCartRecordErrors[keyof DecreaseItemCartRecordErrors];

export type DecreaseItemCartRecordResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type DecreaseItemCartRecordResponse = DecreaseItemCartRecordResponses[keyof DecreaseItemCartRecordResponses];

export type IsProductInWishListsData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        cartId?: string;
        productId?: string;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/WishLists/Contains';
};

export type IsProductInWishListsResponses = {
    /**
     * OK
     */
    200: BooleanEnvelopeReadable;
};

export type IsProductInWishListsResponse = IsProductInWishListsResponses[keyof IsProductInWishListsResponses];

export type WishListExistsData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        wishListId?: string;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/WishLists/Exists';
};

export type WishListExistsResponses = {
    /**
     * OK
     */
    200: BooleanEnvelopeReadable;
};

export type WishListExistsResponse = WishListExistsResponses[keyof WishListExistsResponses];

export type WishListExistsHeadAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        wishListId?: string;
        'api-version'?: string;
    };
    url: '/api/v2/CartService/WishLists/Exists';
};

export type WishListExistsHeadAsyncResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type WishListExistsHeadAsyncResponse = WishListExistsHeadAsyncResponses[keyof WishListExistsHeadAsyncResponses];

export type CreateWishListData = {
    body?: NewWishListRequest;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/WishLists';
};

export type CreateWishListResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type CreateWishListResponse = CreateWishListResponses[keyof CreateWishListResponses];

export type DeleteWishListData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        wishListId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/WishLists/{wishListId}';
};

export type DeleteWishListResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type DeleteWishListResponse = DeleteWishListResponses[keyof DeleteWishListResponses];

export type UpdateProductToWishListData = {
    body?: WishListUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        wishListId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/WishLists/{wishListId}';
};

export type UpdateProductToWishListResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type UpdateProductToWishListResponse = UpdateProductToWishListResponses[keyof UpdateProductToWishListResponses];

export type GetWishListAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        cartId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/WishLists/{cartId}';
};

export type GetWishListAsyncResponses = {
    /**
     * OK
     */
    200: Array<WishListDto>;
};

export type GetWishListAsyncResponse = GetWishListAsyncResponses[keyof GetWishListAsyncResponses];

export type GetCartWishListItemsAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        wishListId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/WishLists/{wishListId}/Records';
};

export type GetCartWishListItemsAsyncResponses = {
    /**
     * OK
     */
    200: Array<WishListItemRecordDto>;
};

export type GetCartWishListItemsAsyncResponse = GetCartWishListItemsAsyncResponses[keyof GetCartWishListItemsAsyncResponses];

export type GetCartWishListDetailsAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        wishListId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/WishLists/{wishListId}/Details';
};

export type GetCartWishListDetailsAsyncResponses = {
    /**
     * OK
     */
    200: WishListDto;
};

export type GetCartWishListDetailsAsyncResponse = GetCartWishListDetailsAsyncResponses[keyof GetCartWishListDetailsAsyncResponses];

export type AddProductToWishListData = {
    body?: ProductToWishListRequest;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/WishLists/Records';
};

export type AddProductToWishListResponses = {
    /**
     * OK
     */
    200: EmptyEnvelopeReadable;
};

export type AddProductToWishListResponse = AddProductToWishListResponses[keyof AddProductToWishListResponses];

export type DeleteWishListRecordData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        recordId: string;
    };
    query?: {
        'api-version'?: string;
    };
    url: '/api/v2/CartService/WishLists/Records/{recordId}';
};

export type DeleteWishListRecordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://{server}` | (string & {});
};