/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type CourseDto = {
    id?: string | null;
    timestamp?: string | null;
    sku?: string | null;
    upc?: string | null;
    ean?: string | null;
    mpn?: string | null;
    skUs?: string | null;
    isbn?: string | null;
    upCs?: string | null;
    eaNs?: string | null;
    asin?: string | null;
    gtin?: string | null;
    mpNs?: string | null;
    part?: string | null;
    name?: string | null;
    isbNs?: string | null;
    asiNs?: string | null;
    gtiNs?: string | null;
    model?: string | null;
    title?: string | null;
    color?: string | null;
    isbN13?: string | null;
    unspsc?: string | null;
    unitId?: string | null;
    series?: string | null;
    barcode?: string | null;
    unspsCs?: string | null;
    pattern?: string | null;
    summary?: string | null;
    brandId?: string | null;
    features?: string | null;
    material?: string | null;
    tenantId?: string | null;
    permalink?: string | null;
    brandName?: string | null;
    languageId?: string | null;
    itemTypeId?: string | null;
    categoryId?: string | null;
    currencyId?: string | null;
    unitGroupId?: string | null;
    description?: string | null;
    ingredients?: string | null;
    releaseDate?: string | null;
    enrollmentId?: string | null;
    supplierCode?: string | null;
    shipsToRules?: string | null;
    purchaseNote?: string | null;
    parentItemId?: string | null;
    itemTypeName?: string | null;
    discriminator?: string | null;
    tariffHeading?: string | null;
    nutritionFacts?: string | null;
    mozaicCoverUrl?: string | null;
    packageContent?: string | null;
    youtubeVideoId?: string | null;
    primaryImageUrl?: string | null;
    longDescription?: string | null;
    measurementUnit?: string | null;
    shortDescription?: string | null;
    googleCategories?: string | null;
    supplierProfileId?: string | null;
    shippingCountryId?: string | null;
    systemRequirements?: string | null;
    customTaxDescription?: string | null;
    officialDescriptionUrl?: string | null;
    energyEfficiencyRating?: string | null;
    pageCoverBackgroundUrl?: string | null;
    primaryGoogleCategoryId?: string | null;
    operatingSystemSupported?: string | null;
    supportedOperatingSystem?: string | null;
    primaryGoogleCategoryName?: string | null;
    hot?: boolean;
    onSale?: boolean;
    auction?: boolean;
    deleted?: boolean;
    digital?: boolean;
    preSale?: boolean;
    taxable?: boolean;
    inStock?: boolean;
    featured?: boolean;
    trending?: boolean;
    lowStock?: boolean;
    published?: boolean;
    byRequest?: boolean;
    onDiscount?: boolean;
    isDailyDeal?: boolean;
    isNewArrival?: boolean;
    isWeeklyDeal?: boolean;
    isBestSeller?: boolean;
    isMonthlyDeal?: boolean;
    hasVariations?: boolean;
    isFixedDiscount?: boolean;
    isDealersChoice?: boolean;
    manageInventory?: boolean;
    isOfficialChoice?: boolean;
    validPrimaryImage?: boolean;
    isDeadlineDiscount?: boolean;
    displayShowcaseTab?: boolean;
    taxIncludedInPrice?: boolean;
    isProductOfTheWeek?: boolean;
    isProductOfTheMonth?: boolean;
    isPercentageDiscount?: boolean;
    displayOnGlobalMozaic?: boolean;
    displayOnBrandsMozaic?: boolean;
    disableDefaultPolicies?: boolean;
    displayOnCategoryMozaic?: boolean;
    displayDescriptionEditor?: boolean;
    displayShortDescriptionEditor?: boolean;
    displayOnBannerMarketingRotation?: boolean;
    auctionEnd?: string | null;
    auctionStart?: string | null;
    publishedDate?: string | null;
    deadlineDiscountFromDate?: string | null;
    deadlineDiscountDueDate?: string | null;
    lastFixedPricesUpdateDateTime?: string | null;
    images?: Array<string> | null;
    viewsCount?: number;
    reviewsCount?: number;
    questionsCount?: number;
    packagedQuantity?: number;
    reviewsAvg?: number | null;
    recurrency?: number;
    currentStock?: number;
    width?: number | null;
    weight?: number | null;
    length?: number | null;
    height?: number | null;
    regularPrice?: number | null;
    discountPrice?: number | null;
    customTaxValue?: number | null;
    discountAmount?: number | null;
    inCartQuantity?: number | null;
    customTaxAmount?: number | null;
    discountPercentage?: number | null;
    customTaxPercentage?: number | null;
    estimatedTaxesInUsd?: number | null;
    estimatedProfitInUsd?: number | null;
    estimatedBasePriceInUsd?: number | null;
    estimatedDiscountsInUsd?: number | null;
    estimatedSurchargesInUsd?: number | null;
    estimatedPaymentTaxInUsd?: number | null;
    estimatedTotalPriceInUsd?: number | null;
    estimatedPaymentCostInUsd?: number | null;
    estimatedDealSavingsInUsd?: number | null;
    estimatedRegularPriceInUsd?: number | null;
    estimatedTaxBasePriceInUsd?: number | null;
    estimatedWithholdingTaxesInUsd?: number | null;
    estimatedDefaultShippingTaxInUsd?: number | null;
    estimatedDefaultShippingCostInUsd?: number | null;
    selectedTags?: Array<string> | null;
    selectedTypes?: Array<string> | null;
    selectedBrands?: Array<string> | null;
    selectedCategories?: Array<string> | null;
    selectedTaxPolicies?: Array<string> | null;
    selectedPricingRules?: Array<string> | null;
    selectedRefundPolicies?: Array<string> | null;
    selectedReturnPolicies?: Array<string> | null;
    selectedPricingPolicies?: Array<string> | null;
    selectedGoogleCategories?: Array<string> | null;
    selectedWarrantyPolicies?: Array<string> | null;
    selectedShipmentPolicies?: Array<string> | null;
    selectedAttributesOptions?: Array<string> | null;
    selectedSellingMarginPolicies?: Array<string> | null;
};

