// This file is auto-generated by @hey-api/openapi-ts

export type AccessTokenResponseReadable = {
    readonly tokenType?: string | null;
    accessToken: string | null;
    expiresIn: number;
    refreshToken: string | null;
};

export type AccessTokenResponseWritable = {
    accessToken: string | null;
    expiresIn: number;
    refreshToken: string | null;
};

export type CognitiveAgentConversationCreateDto = {
    id?: string;
    timestamp?: string;
    channelID?: string | null;
    conversationID?: string | null;
    state?: string | null;
    current?: boolean;
    accountHolderId?: string | null;
    individualId?: string | null;
    organizationId?: string | null;
    receiverBusinessId?: string | null;
};

export type CognitiveAgentConversationDto = {
    id?: string | null;
    timestamp?: string | null;
    cognitiveAgentId?: string | null;
    tenantId?: string | null;
    enrollmentId?: string | null;
    title?: string | null;
    claimed?: boolean;
    current?: boolean;
    channelID?: string | null;
    conversationID?: string | null;
    activityID?: string | null;
    activityFrom?: string | null;
    state?: string | null;
    lastActivity?: string;
    accountHolderId?: string | null;
    individualId?: string | null;
    organizationId?: string | null;
    receiverBusinessId?: string | null;
};

export type CognitiveAgentConversationDtoCollectionQueryParametersReadable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
    readonly isEmpty?: boolean;
};

export type CognitiveAgentConversationDtoCollectionQueryParametersWritable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
};

export type CognitiveAgentConversationDtoListEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    readonly activityId?: string | null;
    result?: Array<CognitiveAgentConversationDto> | null;
};

export type CognitiveAgentConversationDtoListEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    result?: Array<CognitiveAgentConversationDto> | null;
};

export type CognitiveAgentConversationUpdateDto = {
    channelID?: string | null;
    conversationID?: string | null;
    state?: string | null;
    current?: boolean;
    claimed?: boolean;
    accountHolderId?: string | null;
    individualId?: string | null;
    organizationId?: string | null;
    receiverBusinessId?: string | null;
};

export type CognitiveAgentCreateDto = {
    id?: string;
    timestamp?: string;
    name: string;
    avatar?: string | null;
    description?: string | null;
    soul?: string | null;
    providerKey?: string | null;
    modelId?: string | null;
};

export type CognitiveAgentDto = {
    id?: string | null;
    timestamp?: string | null;
    name?: string | null;
    avatar?: string | null;
    description?: string | null;
    soul?: string | null;
    providerKey?: string | null;
    modelId?: string | null;
    tenantId?: string | null;
    enrollmentId?: string | null;
};

export type CognitiveAgentDtoCollectionQueryParametersReadable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
    readonly isEmpty?: boolean;
};

export type CognitiveAgentDtoCollectionQueryParametersWritable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
};

export type CognitiveAgentDtoListEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    readonly activityId?: string | null;
    result?: Array<CognitiveAgentDto> | null;
};

export type CognitiveAgentDtoListEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    result?: Array<CognitiveAgentDto> | null;
};

export type CognitiveAgentMessageDto = {
    id?: string | null;
    timestamp?: string | null;
    cognitiveAgentConversationId?: string | null;
    cognitiveAgentId?: string | null;
    role?: string | null;
    content?: string | null;
    sequence?: number;
    creationDate?: string;
    metadataJson?: string | null;
    aiRunId?: string | null;
    tenantId?: string | null;
    enrollmentId?: string | null;
};

export type CognitiveAgentMessageDtoCollectionQueryParametersReadable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
    readonly isEmpty?: boolean;
};

export type CognitiveAgentMessageDtoCollectionQueryParametersWritable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
};

export type CognitiveAgentMessageDtoListEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    readonly activityId?: string | null;
    result?: Array<CognitiveAgentMessageDto> | null;
};

export type CognitiveAgentMessageDtoListEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    result?: Array<CognitiveAgentMessageDto> | null;
};

export type CognitiveAgentSkillCreateDto = {
    id?: string;
    timestamp?: string;
    cognitiveSkillId: string;
    enabled?: boolean;
    configJson?: string | null;
};

export type CognitiveAgentSkillDto = {
    id?: string | null;
    timestamp?: string | null;
    cognitiveAgentId?: string | null;
    cognitiveSkillId?: string | null;
    enabled?: boolean;
    configJson?: string | null;
    tenantId?: string | null;
    enrollmentId?: string | null;
};

export type CognitiveAgentSkillDtoCollectionQueryParametersReadable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
    readonly isEmpty?: boolean;
};

export type CognitiveAgentSkillDtoCollectionQueryParametersWritable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
};

export type CognitiveAgentSkillDtoListEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    readonly activityId?: string | null;
    result?: Array<CognitiveAgentSkillDto> | null;
};

export type CognitiveAgentSkillDtoListEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    result?: Array<CognitiveAgentSkillDto> | null;
};

export type CognitiveAgentSkillUpdateDto = {
    enabled?: boolean;
    configJson?: string | null;
};

export type CognitiveAgentUpdateDto = {
    name?: string | null;
    avatar?: string | null;
    description?: string | null;
    soul?: string | null;
    providerKey?: string | null;
    modelId?: string | null;
};

export type CognitiveAgentVariableCreateDto = {
    id?: string;
    timestamp?: string;
    key: string;
    value?: string | null;
};

export type CognitiveAgentVariableDto = {
    id?: string | null;
    timestamp?: string | null;
    cognitiveAgentId?: string | null;
    key?: string | null;
    value?: string | null;
    tenantId?: string | null;
    enrollmentId?: string | null;
};

export type CognitiveAgentVariableDtoCollectionQueryParametersReadable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
    readonly isEmpty?: boolean;
};

export type CognitiveAgentVariableDtoCollectionQueryParametersWritable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
};

export type CognitiveAgentVariableDtoListEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    readonly activityId?: string | null;
    result?: Array<CognitiveAgentVariableDto> | null;
};

export type CognitiveAgentVariableDtoListEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    result?: Array<CognitiveAgentVariableDto> | null;
};

export type CognitiveAgentVariableUpdateDto = {
    value?: string | null;
};

export type CognitiveSkillCreateDto = {
    id?: string;
    timestamp?: string;
    name: string;
    description?: string | null;
    toolKey: string;
    configJson?: string | null;
    enabled?: boolean;
};

export type CognitiveSkillDto = {
    id?: string | null;
    timestamp?: string | null;
    name?: string | null;
    description?: string | null;
    toolKey?: string | null;
    configJson?: string | null;
    enabled?: boolean;
    tenantId?: string | null;
    enrollmentId?: string | null;
};

export type CognitiveSkillDtoCollectionQueryParametersReadable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
    readonly isEmpty?: boolean;
};

export type CognitiveSkillDtoCollectionQueryParametersWritable = {
    top?: number | null;
    skip?: number | null;
    count?: boolean;
    filter?: string | null;
    orderBy?: string | null;
    search?: string | null;
    select?: string | null;
    expand?: string | null;
};

export type CognitiveSkillDtoListEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    readonly activityId?: string | null;
    result?: Array<CognitiveSkillDto> | null;
};

export type CognitiveSkillDtoListEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    result?: Array<CognitiveSkillDto> | null;
};

export type CognitiveSkillUpdateDto = {
    name?: string | null;
    description?: string | null;
    toolKey?: string | null;
    configJson?: string | null;
    enabled?: boolean;
};

export type ErrorEnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    readonly activityId?: string | null;
};

export type ErrorEnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
};

export type ForgotPasswordRequest = {
    email: string | null;
};

export type HttpValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors?: {
        [key: string]: Array<string>;
    } | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | ({
        [key: string]: Array<string>;
    } | null) | undefined;
};

export type InfoRequest = {
    newEmail?: string | null;
    newPassword?: string | null;
    oldPassword?: string | null;
};

export type InfoResponse = {
    email: string | null;
    isEmailConfirmed: boolean;
};

export type Int32EnvelopeReadable = {
    readonly isSuccess?: boolean;
    errorMessage?: string | null;
    correlationId?: string | null;
    readonly timestamp?: string;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    readonly activityId?: string | null;
    result?: number;
};

export type Int32EnvelopeWritable = {
    errorMessage?: string | null;
    correlationId?: string | null;
    httpStatus?: number | null;
    errorCode?: string | null;
    validationDetails?: {
        [key: string]: Array<string> | null;
    } | null;
    result?: number;
};

export type LoginRequest = {
    email: string | null;
    password: string | null;
    twoFactorCode?: string | null;
    twoFactorRecoveryCode?: string | null;
};

export type RefreshRequest = {
    refreshToken: string | null;
};

export type RegisterRequest = {
    email: string | null;
    password: string | null;
};

export type ResendConfirmationEmailRequest = {
    email: string | null;
};

export type ResetPasswordRequest = {
    email: string | null;
    resetCode: string | null;
    newPassword: string | null;
};

export type TwoFactorRequest = {
    enable?: boolean | null;
    twoFactorCode?: string | null;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
};

export type TwoFactorResponse = {
    sharedKey: string | null;
    recoveryCodesLeft: number;
    recoveryCodes?: Array<string> | null;
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
};

export type GetCognitiveAgentConversationsAsyncData = {
    body?: CognitiveAgentConversationDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Conversations';
};

export type GetCognitiveAgentConversationsAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentConversationsAsyncError = GetCognitiveAgentConversationsAsyncErrors[keyof GetCognitiveAgentConversationsAsyncErrors];

export type GetCognitiveAgentConversationsAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveAgentConversationDtoListEnvelopeReadable;
};

export type GetCognitiveAgentConversationsAsyncResponse = GetCognitiveAgentConversationsAsyncResponses[keyof GetCognitiveAgentConversationsAsyncResponses];

export type CreateCognitiveAgentConversationAsyncData = {
    body?: CognitiveAgentConversationCreateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Conversations';
};

export type CreateCognitiveAgentConversationAsyncErrors = {
    /**
     * Bad Request
     */
    400: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type CreateCognitiveAgentConversationAsyncError = CreateCognitiveAgentConversationAsyncErrors[keyof CreateCognitiveAgentConversationAsyncErrors];

export type CreateCognitiveAgentConversationAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveAgentConversationsCountAsyncData = {
    body?: CognitiveAgentConversationDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Conversations/Count';
};

export type GetCognitiveAgentConversationsCountAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentConversationsCountAsyncError = GetCognitiveAgentConversationsCountAsyncErrors[keyof GetCognitiveAgentConversationsCountAsyncErrors];

export type GetCognitiveAgentConversationsCountAsyncResponses = {
    /**
     * OK
     */
    200: Int32EnvelopeReadable;
};

export type GetCognitiveAgentConversationsCountAsyncResponse = GetCognitiveAgentConversationsCountAsyncResponses[keyof GetCognitiveAgentConversationsCountAsyncResponses];

export type DeleteCognitiveAgentConversationAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Conversations/{id}';
};

export type DeleteCognitiveAgentConversationAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type DeleteCognitiveAgentConversationAsyncError = DeleteCognitiveAgentConversationAsyncErrors[keyof DeleteCognitiveAgentConversationAsyncErrors];

export type DeleteCognitiveAgentConversationAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveAgentConversationByIdAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Conversations/{id}';
};

export type GetCognitiveAgentConversationByIdAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentConversationByIdAsyncError = GetCognitiveAgentConversationByIdAsyncErrors[keyof GetCognitiveAgentConversationByIdAsyncErrors];

export type GetCognitiveAgentConversationByIdAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveAgentConversationDto;
};

export type GetCognitiveAgentConversationByIdAsyncResponse = GetCognitiveAgentConversationByIdAsyncResponses[keyof GetCognitiveAgentConversationByIdAsyncResponses];

export type UpdateCognitiveAgentConversationAsyncData = {
    body?: CognitiveAgentConversationUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Conversations/{id}';
};

export type UpdateCognitiveAgentConversationAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type UpdateCognitiveAgentConversationAsyncError = UpdateCognitiveAgentConversationAsyncErrors[keyof UpdateCognitiveAgentConversationAsyncErrors];

export type UpdateCognitiveAgentConversationAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveAgentMessagesAsyncData = {
    body?: CognitiveAgentMessageDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        conversationId: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Conversations/{conversationId}/Messages';
};

export type GetCognitiveAgentMessagesAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentMessagesAsyncError = GetCognitiveAgentMessagesAsyncErrors[keyof GetCognitiveAgentMessagesAsyncErrors];

export type GetCognitiveAgentMessagesAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveAgentMessageDtoListEnvelopeReadable;
};

export type GetCognitiveAgentMessagesAsyncResponse = GetCognitiveAgentMessagesAsyncResponses[keyof GetCognitiveAgentMessagesAsyncResponses];

export type GetCognitiveAgentMessagesCountAsyncData = {
    body?: CognitiveAgentMessageDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        conversationId: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Conversations/{conversationId}/Messages/Count';
};

export type GetCognitiveAgentMessagesCountAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentMessagesCountAsyncError = GetCognitiveAgentMessagesCountAsyncErrors[keyof GetCognitiveAgentMessagesCountAsyncErrors];

export type GetCognitiveAgentMessagesCountAsyncResponses = {
    /**
     * OK
     */
    200: Int32EnvelopeReadable;
};

export type GetCognitiveAgentMessagesCountAsyncResponse = GetCognitiveAgentMessagesCountAsyncResponses[keyof GetCognitiveAgentMessagesCountAsyncResponses];

export type GetCognitiveAgentMessageByIdAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        conversationId: string;
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Conversations/{conversationId}/Messages/{id}';
};

export type GetCognitiveAgentMessageByIdAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentMessageByIdAsyncError = GetCognitiveAgentMessageByIdAsyncErrors[keyof GetCognitiveAgentMessageByIdAsyncErrors];

export type GetCognitiveAgentMessageByIdAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveAgentMessageDto;
};

export type GetCognitiveAgentMessageByIdAsyncResponse = GetCognitiveAgentMessageByIdAsyncResponses[keyof GetCognitiveAgentMessageByIdAsyncResponses];

export type GetCognitiveAgentsAsyncData = {
    body?: CognitiveAgentDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents';
};

export type GetCognitiveAgentsAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentsAsyncError = GetCognitiveAgentsAsyncErrors[keyof GetCognitiveAgentsAsyncErrors];

export type GetCognitiveAgentsAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveAgentDtoListEnvelopeReadable;
};

export type GetCognitiveAgentsAsyncResponse = GetCognitiveAgentsAsyncResponses[keyof GetCognitiveAgentsAsyncResponses];

export type CreateCognitiveAgentAsyncData = {
    body?: CognitiveAgentCreateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents';
};

export type CreateCognitiveAgentAsyncErrors = {
    /**
     * Bad Request
     */
    400: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type CreateCognitiveAgentAsyncError = CreateCognitiveAgentAsyncErrors[keyof CreateCognitiveAgentAsyncErrors];

export type CreateCognitiveAgentAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveAgentsCountAsyncData = {
    body?: CognitiveAgentDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/Count';
};

export type GetCognitiveAgentsCountAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentsCountAsyncError = GetCognitiveAgentsCountAsyncErrors[keyof GetCognitiveAgentsCountAsyncErrors];

export type GetCognitiveAgentsCountAsyncResponses = {
    /**
     * OK
     */
    200: Int32EnvelopeReadable;
};

export type GetCognitiveAgentsCountAsyncResponse = GetCognitiveAgentsCountAsyncResponses[keyof GetCognitiveAgentsCountAsyncResponses];

export type DeleteCognitiveAgentAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{id}';
};

export type DeleteCognitiveAgentAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type DeleteCognitiveAgentAsyncError = DeleteCognitiveAgentAsyncErrors[keyof DeleteCognitiveAgentAsyncErrors];

export type DeleteCognitiveAgentAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveAgentByIdAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{id}';
};

export type GetCognitiveAgentByIdAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentByIdAsyncError = GetCognitiveAgentByIdAsyncErrors[keyof GetCognitiveAgentByIdAsyncErrors];

export type GetCognitiveAgentByIdAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveAgentDto;
};

export type GetCognitiveAgentByIdAsyncResponse = GetCognitiveAgentByIdAsyncResponses[keyof GetCognitiveAgentByIdAsyncResponses];

export type UpdateCognitiveAgentAsyncData = {
    body?: CognitiveAgentUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{id}';
};

export type UpdateCognitiveAgentAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type UpdateCognitiveAgentAsyncError = UpdateCognitiveAgentAsyncErrors[keyof UpdateCognitiveAgentAsyncErrors];

export type UpdateCognitiveAgentAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveAgentSkillsAsyncData = {
    body?: CognitiveAgentSkillDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Skills';
};

export type GetCognitiveAgentSkillsAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentSkillsAsyncError = GetCognitiveAgentSkillsAsyncErrors[keyof GetCognitiveAgentSkillsAsyncErrors];

export type GetCognitiveAgentSkillsAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveAgentSkillDtoListEnvelopeReadable;
};

export type GetCognitiveAgentSkillsAsyncResponse = GetCognitiveAgentSkillsAsyncResponses[keyof GetCognitiveAgentSkillsAsyncResponses];

export type CreateCognitiveAgentSkillAsyncData = {
    body?: CognitiveAgentSkillCreateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Skills';
};

export type CreateCognitiveAgentSkillAsyncErrors = {
    /**
     * Bad Request
     */
    400: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type CreateCognitiveAgentSkillAsyncError = CreateCognitiveAgentSkillAsyncErrors[keyof CreateCognitiveAgentSkillAsyncErrors];

export type CreateCognitiveAgentSkillAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveAgentSkillsCountAsyncData = {
    body?: CognitiveAgentSkillDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Skills/Count';
};

export type GetCognitiveAgentSkillsCountAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentSkillsCountAsyncError = GetCognitiveAgentSkillsCountAsyncErrors[keyof GetCognitiveAgentSkillsCountAsyncErrors];

export type GetCognitiveAgentSkillsCountAsyncResponses = {
    /**
     * OK
     */
    200: Int32EnvelopeReadable;
};

export type GetCognitiveAgentSkillsCountAsyncResponse = GetCognitiveAgentSkillsCountAsyncResponses[keyof GetCognitiveAgentSkillsCountAsyncResponses];

export type DeleteCognitiveAgentSkillAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Skills/{id}';
};

export type DeleteCognitiveAgentSkillAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type DeleteCognitiveAgentSkillAsyncError = DeleteCognitiveAgentSkillAsyncErrors[keyof DeleteCognitiveAgentSkillAsyncErrors];

export type DeleteCognitiveAgentSkillAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveAgentSkillByIdAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Skills/{id}';
};

export type GetCognitiveAgentSkillByIdAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentSkillByIdAsyncError = GetCognitiveAgentSkillByIdAsyncErrors[keyof GetCognitiveAgentSkillByIdAsyncErrors];

export type GetCognitiveAgentSkillByIdAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveAgentSkillDto;
};

export type GetCognitiveAgentSkillByIdAsyncResponse = GetCognitiveAgentSkillByIdAsyncResponses[keyof GetCognitiveAgentSkillByIdAsyncResponses];

export type UpdateCognitiveAgentSkillAsyncData = {
    body?: CognitiveAgentSkillUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Skills/{id}';
};

export type UpdateCognitiveAgentSkillAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type UpdateCognitiveAgentSkillAsyncError = UpdateCognitiveAgentSkillAsyncErrors[keyof UpdateCognitiveAgentSkillAsyncErrors];

export type UpdateCognitiveAgentSkillAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveAgentVariablesAsyncData = {
    body?: CognitiveAgentVariableDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables';
};

export type GetCognitiveAgentVariablesAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentVariablesAsyncError = GetCognitiveAgentVariablesAsyncErrors[keyof GetCognitiveAgentVariablesAsyncErrors];

export type GetCognitiveAgentVariablesAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveAgentVariableDtoListEnvelopeReadable;
};

export type GetCognitiveAgentVariablesAsyncResponse = GetCognitiveAgentVariablesAsyncResponses[keyof GetCognitiveAgentVariablesAsyncResponses];

export type CreateCognitiveAgentVariableAsyncData = {
    body?: CognitiveAgentVariableCreateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables';
};

export type CreateCognitiveAgentVariableAsyncErrors = {
    /**
     * Bad Request
     */
    400: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type CreateCognitiveAgentVariableAsyncError = CreateCognitiveAgentVariableAsyncErrors[keyof CreateCognitiveAgentVariableAsyncErrors];

export type CreateCognitiveAgentVariableAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveAgentVariablesCountAsyncData = {
    body?: CognitiveAgentVariableDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/Count';
};

export type GetCognitiveAgentVariablesCountAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentVariablesCountAsyncError = GetCognitiveAgentVariablesCountAsyncErrors[keyof GetCognitiveAgentVariablesCountAsyncErrors];

export type GetCognitiveAgentVariablesCountAsyncResponses = {
    /**
     * OK
     */
    200: Int32EnvelopeReadable;
};

export type GetCognitiveAgentVariablesCountAsyncResponse = GetCognitiveAgentVariablesCountAsyncResponses[keyof GetCognitiveAgentVariablesCountAsyncResponses];

export type DeleteCognitiveAgentVariableAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/{id}';
};

export type DeleteCognitiveAgentVariableAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type DeleteCognitiveAgentVariableAsyncError = DeleteCognitiveAgentVariableAsyncErrors[keyof DeleteCognitiveAgentVariableAsyncErrors];

export type DeleteCognitiveAgentVariableAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveAgentVariableByIdAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/{id}';
};

export type GetCognitiveAgentVariableByIdAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCognitiveAgentVariableByIdAsyncError = GetCognitiveAgentVariableByIdAsyncErrors[keyof GetCognitiveAgentVariableByIdAsyncErrors];

export type GetCognitiveAgentVariableByIdAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveAgentVariableDto;
};

export type GetCognitiveAgentVariableByIdAsyncResponse = GetCognitiveAgentVariableByIdAsyncResponses[keyof GetCognitiveAgentVariableByIdAsyncResponses];

export type UpdateCognitiveAgentVariableAsyncData = {
    body?: CognitiveAgentVariableUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        agentId: string;
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/{id}';
};

export type UpdateCognitiveAgentVariableAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type UpdateCognitiveAgentVariableAsyncError = UpdateCognitiveAgentVariableAsyncErrors[keyof UpdateCognitiveAgentVariableAsyncErrors];

export type UpdateCognitiveAgentVariableAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveSkillsAsyncData = {
    body?: CognitiveSkillDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveSkills';
};

export type GetCognitiveSkillsAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveSkillsAsyncError = GetCognitiveSkillsAsyncErrors[keyof GetCognitiveSkillsAsyncErrors];

export type GetCognitiveSkillsAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveSkillDtoListEnvelopeReadable;
};

export type GetCognitiveSkillsAsyncResponse = GetCognitiveSkillsAsyncResponses[keyof GetCognitiveSkillsAsyncResponses];

export type CreateCognitiveSkillAsyncData = {
    body?: CognitiveSkillCreateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveSkills';
};

export type CreateCognitiveSkillAsyncErrors = {
    /**
     * Bad Request
     */
    400: ErrorEnvelopeReadable;
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type CreateCognitiveSkillAsyncError = CreateCognitiveSkillAsyncErrors[keyof CreateCognitiveSkillAsyncErrors];

export type CreateCognitiveSkillAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveSkillsCountAsyncData = {
    body?: CognitiveSkillDtoCollectionQueryParametersWritable;
    headers?: {
        'x-api-version'?: string;
    };
    path?: never;
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveSkills/Count';
};

export type GetCognitiveSkillsCountAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
};

export type GetCognitiveSkillsCountAsyncError = GetCognitiveSkillsCountAsyncErrors[keyof GetCognitiveSkillsCountAsyncErrors];

export type GetCognitiveSkillsCountAsyncResponses = {
    /**
     * OK
     */
    200: Int32EnvelopeReadable;
};

export type GetCognitiveSkillsCountAsyncResponse = GetCognitiveSkillsCountAsyncResponses[keyof GetCognitiveSkillsCountAsyncResponses];

export type DeleteCognitiveSkillAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveSkills/{id}';
};

export type DeleteCognitiveSkillAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type DeleteCognitiveSkillAsyncError = DeleteCognitiveSkillAsyncErrors[keyof DeleteCognitiveSkillAsyncErrors];

export type DeleteCognitiveSkillAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCognitiveSkillByIdAsyncData = {
    body?: never;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveSkills/{id}';
};

export type GetCognitiveSkillByIdAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type GetCognitiveSkillByIdAsyncError = GetCognitiveSkillByIdAsyncErrors[keyof GetCognitiveSkillByIdAsyncErrors];

export type GetCognitiveSkillByIdAsyncResponses = {
    /**
     * OK
     */
    200: CognitiveSkillDto;
};

export type GetCognitiveSkillByIdAsyncResponse = GetCognitiveSkillByIdAsyncResponses[keyof GetCognitiveSkillByIdAsyncResponses];

export type UpdateCognitiveSkillAsyncData = {
    body?: CognitiveSkillUpdateDto;
    headers?: {
        'x-api-version'?: string;
    };
    path: {
        id: string;
    };
    query: {
        tenantId: string;
        'api-version'?: string;
    };
    url: '/api/v2/IntelligenceService/CognitiveSkills/{id}';
};

export type UpdateCognitiveSkillAsyncErrors = {
    /**
     * Forbidden
     */
    403: ErrorEnvelopeReadable;
    /**
     * Not Found
     */
    404: ErrorEnvelopeReadable;
};

export type UpdateCognitiveSkillAsyncError = UpdateCognitiveSkillAsyncErrors[keyof UpdateCognitiveSkillAsyncErrors];

export type UpdateCognitiveSkillAsyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/version';
};

export type GetVersionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV2AiServiceAgentsByAgentIdAguiData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/v2/AIService/Agents/{agentId}/agui';
};

export type PostApiV2AiServiceAgentsByAgentIdAguiResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hello';
};

export type GetHelloResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostRegisterError = PostRegisterErrors[keyof PostRegisterErrors];

export type PostRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostLoginData = {
    body: LoginRequest;
    path?: never;
    query?: {
        useCookies?: boolean;
        useSessionCookies?: boolean;
    };
    url: '/login';
};

export type PostLoginResponses = {
    /**
     * OK
     */
    200: AccessTokenResponseReadable;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/refresh';
};

export type PostRefreshResponses = {
    /**
     * OK
     */
    200: AccessTokenResponseReadable;
};

export type PostRefreshResponse = PostRefreshResponses[keyof PostRefreshResponses];

export type MapIdentityApiConfirmEmailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
        code: string;
        changedEmail?: string;
    };
    url: '/confirmEmail';
};

export type MapIdentityApiConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostResendConfirmationEmailData = {
    body: ResendConfirmationEmailRequest;
    path?: never;
    query?: never;
    url: '/resendConfirmationEmail';
};

export type PostResendConfirmationEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/forgotPassword';
};

export type PostForgotPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostForgotPasswordError = PostForgotPasswordErrors[keyof PostForgotPasswordErrors];

export type PostForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/resetPassword';
};

export type PostResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostResetPasswordError = PostResetPasswordErrors[keyof PostResetPasswordErrors];

export type PostResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostManage2FaData = {
    body: TwoFactorRequest;
    path?: never;
    query?: never;
    url: '/manage/2fa';
};

export type PostManage2FaErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostManage2FaError = PostManage2FaErrors[keyof PostManage2FaErrors];

export type PostManage2FaResponses = {
    /**
     * OK
     */
    200: TwoFactorResponse;
};

export type PostManage2FaResponse = PostManage2FaResponses[keyof PostManage2FaResponses];

export type GetManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type GetManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetManageInfoError = GetManageInfoErrors[keyof GetManageInfoErrors];

export type GetManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type GetManageInfoResponse = GetManageInfoResponses[keyof GetManageInfoResponses];

export type PostManageInfoData = {
    body: InfoRequest;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type PostManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostManageInfoError = PostManageInfoErrors[keyof PostManageInfoErrors];

export type PostManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type PostManageInfoResponse = PostManageInfoResponses[keyof PostManageInfoResponses];

export type PostAccountPerformExternalLoginData = {
    body?: {
        provider?: string;
        returnUrl?: string;
    };
    path?: never;
    query?: never;
    url: '/Account/PerformExternalLogin';
};

export type PostAccountPerformExternalLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAccountLogoutData = {
    body?: {
        returnUrl?: string;
    };
    path?: never;
    query?: never;
    url: '/Account/Logout';
};

export type PostAccountLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAccountManageLinkExternalLoginData = {
    body?: {
        provider?: string;
    };
    path?: never;
    query?: never;
    url: '/Account/Manage/LinkExternalLogin';
};

export type PostAccountManageLinkExternalLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAccountManageDownloadPersonalDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Account/Manage/DownloadPersonalData';
};

export type PostAccountManageDownloadPersonalDataResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://{server}` | (string & {});
};